let specified_path="./";

export function setPath(new_path)
{
    specified_path=new_path;
}

var createGlobalModule = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(createGlobalModule) {
  createGlobalModule = createGlobalModule || {};


var Module;Module||(Module=typeof createGlobalModule !== 'undefined' ? createGlobalModule : {});var readyPromiseResolve,readyPromiseReject;Module.ready=new Promise(function(a,b){readyPromiseResolve=a;readyPromiseReject=b});Module.locateFile=function(a){return specified_path};var moduleOverrides=Object.assign({},Module),arguments_=[],thisProgram="./this.program",quit_=(a,b)=>{throw b;},ENVIRONMENT_IS_WEB=!0,ENVIRONMENT_IS_WORKER=!1,scriptDirectory="";
function locateFile(a){return Module.locateFile?Module.locateFile(a,scriptDirectory):scriptDirectory+a}var read_,readAsync,readBinary,setWindowTitle;
if(ENVIRONMENT_IS_WEB||ENVIRONMENT_IS_WORKER)ENVIRONMENT_IS_WORKER?scriptDirectory=self.location.href:"undefined"!=typeof document&&document.currentScript&&(scriptDirectory=document.currentScript.src),_scriptDir&&(scriptDirectory=_scriptDir),scriptDirectory=0!==scriptDirectory.indexOf("blob:")?scriptDirectory.substr(0,scriptDirectory.replace(/[?#].*/,"").lastIndexOf("/")+1):"",read_=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ENVIRONMENT_IS_WORKER&&(readBinary=
a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),readAsync=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},setWindowTitle=a=>document.title=a;var out=Module.print||console.log.bind(console),err=Module.printErr||console.warn.bind(console);Object.assign(Module,moduleOverrides);
moduleOverrides=null;Module.arguments&&(arguments_=Module.arguments);Module.thisProgram&&(thisProgram=Module.thisProgram);Module.quit&&(quit_=Module.quit);var wasmBinary;Module.wasmBinary&&(wasmBinary=Module.wasmBinary);var noExitRuntime=Module.noExitRuntime||!0;"object"!=typeof WebAssembly&&abort("no native wasm support detected");var wasmMemory,ABORT=!1,EXITSTATUS;function assert(a,b){a||abort(b)}var UTF8Decoder="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function UTF8ArrayToString(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&UTF8Decoder)return UTF8Decoder.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function UTF8ToString(a,b){return a?UTF8ArrayToString(HEAPU8,a,b):""}
function stringToUTF8Array(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var h=a.charCodeAt(++f);k=65536+((k&1023)<<10)|h&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function stringToUTF8(a,b,c){return stringToUTF8Array(a,HEAPU8,b,c)}function lengthBytesUTF8(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var buffer,HEAP8,HEAPU8,HEAP16,HEAPU16,HEAP32,HEAPU32,HEAPF32,HEAPF64;
function updateGlobalBufferAndViews(a){buffer=a;Module.HEAP8=HEAP8=new Int8Array(a);Module.HEAP16=HEAP16=new Int16Array(a);Module.HEAP32=HEAP32=new Int32Array(a);Module.HEAPU8=HEAPU8=new Uint8Array(a);Module.HEAPU16=HEAPU16=new Uint16Array(a);Module.HEAPU32=HEAPU32=new Uint32Array(a);Module.HEAPF32=HEAPF32=new Float32Array(a);Module.HEAPF64=HEAPF64=new Float64Array(a)}
var INITIAL_MEMORY=Module.INITIAL_MEMORY||16777216,wasmTable,__ATPRERUN__=[],__ATINIT__=[],__ATMAIN__=[],__ATPOSTRUN__=[],runtimeInitialized=!1;function keepRuntimeAlive(){return noExitRuntime}function preRun(){if(Module.preRun)for("function"==typeof Module.preRun&&(Module.preRun=[Module.preRun]);Module.preRun.length;)addOnPreRun(Module.preRun.shift());callRuntimeCallbacks(__ATPRERUN__)}function initRuntime(){runtimeInitialized=!0;callRuntimeCallbacks(__ATINIT__)}
function preMain(){callRuntimeCallbacks(__ATMAIN__)}function postRun(){if(Module.postRun)for("function"==typeof Module.postRun&&(Module.postRun=[Module.postRun]);Module.postRun.length;)addOnPostRun(Module.postRun.shift());callRuntimeCallbacks(__ATPOSTRUN__)}function addOnPreRun(a){__ATPRERUN__.unshift(a)}function addOnInit(a){__ATINIT__.unshift(a)}function addOnPostRun(a){__ATPOSTRUN__.unshift(a)}var runDependencies=0,runDependencyWatcher=null,dependenciesFulfilled=null;
function addRunDependency(a){runDependencies++;Module.monitorRunDependencies&&Module.monitorRunDependencies(runDependencies)}function removeRunDependency(a){runDependencies--;Module.monitorRunDependencies&&Module.monitorRunDependencies(runDependencies);0==runDependencies&&(null!==runDependencyWatcher&&(clearInterval(runDependencyWatcher),runDependencyWatcher=null),dependenciesFulfilled&&(a=dependenciesFulfilled,dependenciesFulfilled=null,a()))}
function abort(a){if(Module.onAbort)Module.onAbort(a);a="Aborted("+a+")";err(a);ABORT=!0;EXITSTATUS=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");readyPromiseReject(a);throw a;}var dataURIPrefix="data:application/octet-stream;base64,";function isDataURI(a){return a.startsWith(dataURIPrefix)}var wasmBinaryFile;
Module.locateFile?(wasmBinaryFile="VIRELANG.wasm",isDataURI(wasmBinaryFile)||(wasmBinaryFile=locateFile(wasmBinaryFile))):wasmBinaryFile=(new URL("VIRELANG.wasm",import.meta.url)).toString();function getBinary(a){try{if(a==wasmBinaryFile&&wasmBinary)return new Uint8Array(wasmBinary);if(readBinary)return readBinary(a);throw"both async and sync fetching of the wasm failed";}catch(b){abort(b)}}
function getBinaryPromise(){return wasmBinary||!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER||"function"!=typeof fetch?Promise.resolve().then(function(){return getBinary(wasmBinaryFile)}):fetch(wasmBinaryFile,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+wasmBinaryFile+"'";return a.arrayBuffer()}).catch(function(){return getBinary(wasmBinaryFile)})}
function createWasm(){function a(e,f){Module.asm=e.exports;wasmMemory=Module.asm.Ka;updateGlobalBufferAndViews(wasmMemory.buffer);wasmTable=Module.asm.Oa;addOnInit(Module.asm.La);removeRunDependency("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return getBinaryPromise().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){err("failed to asynchronously prepare wasm: "+f);abort(f)})}var d={a:asmLibraryArg};addRunDependency("wasm-instantiate");
if(Module.instantiateWasm)try{return Module.instantiateWasm(d,a)}catch(e){err("Module.instantiateWasm callback failed with error: "+e),readyPromiseReject(e)}(function(){return wasmBinary||"function"!=typeof WebAssembly.instantiateStreaming||isDataURI(wasmBinaryFile)||"function"!=typeof fetch?c(b):fetch(wasmBinaryFile,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){err("wasm streaming compile failed: "+f);err("falling back to ArrayBuffer instantiation");
return c(b)})})})().catch(readyPromiseReject);return{}}function ExitStatus(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function callRuntimeCallbacks(a){for(;0<a.length;)a.shift()(Module)}function getWasmTableEntry(a){return wasmTable.get(a)}function ___call_sighandler(a,b){getWasmTableEntry(a)(b)}function ___cxa_allocate_exception(a){return _malloc(a+24)+24}var exceptionCaught=[];function exception_addRef(a){a.add_ref()}var uncaughtExceptionCount=0;
function ___cxa_begin_catch(a){a=new ExceptionInfo(a);a.get_caught()||(a.set_caught(!0),uncaughtExceptionCount--);a.set_rethrown(!1);exceptionCaught.push(a);exception_addRef(a);return a.get_exception_ptr()}var exceptionLast=0;
function ExceptionInfo(a){this.excPtr=a;this.ptr=a-24;this.set_type=function(b){HEAPU32[this.ptr+4>>2]=b};this.get_type=function(){return HEAPU32[this.ptr+4>>2]};this.set_destructor=function(b){HEAPU32[this.ptr+8>>2]=b};this.get_destructor=function(){return HEAPU32[this.ptr+8>>2]};this.set_refcount=function(b){HEAP32[this.ptr>>2]=b};this.set_caught=function(b){HEAP8[this.ptr+12>>0]=b?1:0};this.get_caught=function(){return 0!=HEAP8[this.ptr+12>>0]};this.set_rethrown=function(b){HEAP8[this.ptr+13>>
0]=b?1:0};this.get_rethrown=function(){return 0!=HEAP8[this.ptr+13>>0]};this.init=function(b,c){this.set_adjusted_ptr(0);this.set_type(b);this.set_destructor(c);this.set_refcount(0);this.set_caught(!1);this.set_rethrown(!1)};this.add_ref=function(){HEAP32[this.ptr>>2]+=1};this.release_ref=function(){var b=HEAP32[this.ptr>>2];HEAP32[this.ptr>>2]=b-1;return 1===b};this.set_adjusted_ptr=function(b){HEAPU32[this.ptr+16>>2]=b};this.get_adjusted_ptr=function(){return HEAPU32[this.ptr+16>>2]};this.get_exception_ptr=
function(){if(___cxa_is_pointer_type(this.get_type()))return HEAPU32[this.excPtr>>2];var b=this.get_adjusted_ptr();return 0!==b?b:this.excPtr}}function ___cxa_free_exception(a){try{return _free((new ExceptionInfo(a)).ptr)}catch(b){}}function exception_decRef(a){if(a.release_ref()&&!a.get_rethrown()){var b=a.get_destructor();b&&getWasmTableEntry(b)(a.excPtr);___cxa_free_exception(a.excPtr)}}function ___cxa_end_catch(){_setThrew(0);var a=exceptionCaught.pop();exception_decRef(a);exceptionLast=0}
function ___resumeException(a){exceptionLast||(exceptionLast=a);throw a;}function ___cxa_find_matching_catch_2(){var a=exceptionLast;if(!a)return setTempRet0(0),0;var b=new ExceptionInfo(a);b.set_adjusted_ptr(a);var c=b.get_type();if(!c)return setTempRet0(0),a;for(var d=0;d<arguments.length;d++){var e=arguments[d];if(0===e||e===c)break;if(___cxa_can_catch(e,c,b.ptr+16))return setTempRet0(e),a}setTempRet0(c);return a}
function ___cxa_find_matching_catch_3(){var a=exceptionLast;if(!a)return setTempRet0(0),0;var b=new ExceptionInfo(a);b.set_adjusted_ptr(a);var c=b.get_type();if(!c)return setTempRet0(0),a;for(var d=0;d<arguments.length;d++){var e=arguments[d];if(0===e||e===c)break;if(___cxa_can_catch(e,c,b.ptr+16))return setTempRet0(e),a}setTempRet0(c);return a}
function ___cxa_rethrow(){var a=exceptionCaught.pop();a||abort("no exception to throw");var b=a.excPtr;a.get_rethrown()||(exceptionCaught.push(a),a.set_rethrown(!0),a.set_caught(!1),uncaughtExceptionCount++);exceptionLast=b;throw b;}function ___cxa_throw(a,b,c){(new ExceptionInfo(a)).init(b,c);exceptionLast=a;uncaughtExceptionCount++;throw a;}function ___cxa_uncaught_exceptions(){return uncaughtExceptionCount}
var SYSCALLS={varargs:void 0,get:function(){SYSCALLS.varargs+=4;return HEAP32[SYSCALLS.varargs-4>>2]},getStr:function(a){return UTF8ToString(a)}};function ___syscall_faccessat(a,b,c,d){}function ___syscall_fstat64(a,b){}function ___syscall_getcwd(a,b){}function ___syscall_lstat64(a,b){}function ___syscall_newfstatat(a,b,c,d){}function ___syscall_openat(a,b,c,d){SYSCALLS.varargs=d}function ___syscall_rmdir(a){}function ___syscall_stat64(a,b){}function ___syscall_unlinkat(a,b,c){}
function __embind_register_bigint(a,b,c,d,e){}function getShiftFromSize(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}function embind_init_charCodes(){for(var a=Array(256),b=0;256>b;++b)a[b]=String.fromCharCode(b);embind_charCodes=a}var embind_charCodes=void 0;function readLatin1String(a){for(var b="";HEAPU8[a];)b+=embind_charCodes[HEAPU8[a++]];return b}
var awaitingDependencies={},registeredTypes={},typeDependencies={},char_0=48,char_9=57;function makeLegalFunctionName(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return b>=char_0&&b<=char_9?"_"+a:a}function createNamedFunction(a,b){a=makeLegalFunctionName(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function extendError(a,b){var c=createNamedFunction(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var BindingError=void 0;function throwBindingError(a){throw new BindingError(a);}var InternalError=void 0;
function throwInternalError(a){throw new InternalError(a);}
function whenDependentTypesAreResolved(a,b,c){function d(h){h=c(h);h.length!==a.length&&throwInternalError("Mismatched type converter count");for(var l=0;l<a.length;++l)registerType(a[l],h[l])}a.forEach(function(h){typeDependencies[h]=b});var e=Array(b.length),f=[],k=0;b.forEach((h,l)=>{registeredTypes.hasOwnProperty(h)?e[l]=registeredTypes[h]:(f.push(h),awaitingDependencies.hasOwnProperty(h)||(awaitingDependencies[h]=[]),awaitingDependencies[h].push(()=>{e[l]=registeredTypes[h];++k;k===f.length&&
d(e)}))});0===f.length&&d(e)}
function registerType(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||throwBindingError('type "'+d+'" must have a positive integer typeid pointer');if(registeredTypes.hasOwnProperty(a)){if(c.ignoreDuplicateRegistrations)return;throwBindingError("Cannot register type '"+d+"' twice")}registeredTypes[a]=b;delete typeDependencies[a];awaitingDependencies.hasOwnProperty(a)&&(b=awaitingDependencies[a],delete awaitingDependencies[a],
b.forEach(e=>e()))}function __embind_register_bool(a,b,c,d,e){var f=getShiftFromSize(c);b=readLatin1String(b);registerType(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=HEAP8;else if(2===c)h=HEAP16;else if(4===c)h=HEAP32;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>f])},destructorFunction:null})}
function ClassHandle_isAliasOf(a){if(!(this instanceof ClassHandle&&a instanceof ClassHandle))return!1;var b=this.$$.ptrType.registeredClass,c=this.$$.ptr,d=a.$$.ptrType.registeredClass;for(a=a.$$.ptr;b.baseClass;)c=b.upcast(c),b=b.baseClass;for(;d.baseClass;)a=d.upcast(a),d=d.baseClass;return b===d&&c===a}
function shallowCopyInternalPointer(a){return{count:a.count,deleteScheduled:a.deleteScheduled,preservePointerOnDelete:a.preservePointerOnDelete,ptr:a.ptr,ptrType:a.ptrType,smartPtr:a.smartPtr,smartPtrType:a.smartPtrType}}function throwInstanceAlreadyDeleted(a){throwBindingError(a.$$.ptrType.registeredClass.name+" instance already deleted")}var finalizationRegistry=!1;function detachFinalizer(a){}
function runDestructor(a){a.smartPtr?a.smartPtrType.rawDestructor(a.smartPtr):a.ptrType.registeredClass.rawDestructor(a.ptr)}function releaseClassHandle(a){--a.count.value;0===a.count.value&&runDestructor(a)}function downcastPointer(a,b,c){if(b===c)return a;if(void 0===c.baseClass)return null;a=downcastPointer(a,b,c.baseClass);return null===a?null:c.downcast(a)}var registeredPointers={};function getInheritedInstanceCount(){return Object.keys(registeredInstances).length}
function getLiveInheritedInstances(){var a=[],b;for(b in registeredInstances)registeredInstances.hasOwnProperty(b)&&a.push(registeredInstances[b]);return a}var deletionQueue=[];function flushPendingDeletes(){for(;deletionQueue.length;){var a=deletionQueue.pop();a.$$.deleteScheduled=!1;a["delete"]()}}var delayFunction=void 0;function setDelayFunction(a){delayFunction=a;deletionQueue.length&&delayFunction&&delayFunction(flushPendingDeletes)}
function init_embind(){Module.getInheritedInstanceCount=getInheritedInstanceCount;Module.getLiveInheritedInstances=getLiveInheritedInstances;Module.flushPendingDeletes=flushPendingDeletes;Module.setDelayFunction=setDelayFunction}var registeredInstances={};function getBasestPointer(a,b){for(void 0===b&&throwBindingError("ptr should not be undefined");a.baseClass;)b=a.upcast(b),a=a.baseClass;return b}function getInheritedInstance(a,b){b=getBasestPointer(a,b);return registeredInstances[b]}
function makeClassHandle(a,b){b.ptrType&&b.ptr||throwInternalError("makeClassHandle requires ptr and ptrType");!!b.smartPtrType!==!!b.smartPtr&&throwInternalError("Both smartPtrType and smartPtr must be specified");b.count={value:1};return attachFinalizer(Object.create(a,{$$:{value:b}}))}
function RegisteredPointer_fromWireType(a){function b(){return this.isSmartPointer?makeClassHandle(this.registeredClass.instancePrototype,{ptrType:this.pointeeType,ptr:c,smartPtrType:this,smartPtr:a}):makeClassHandle(this.registeredClass.instancePrototype,{ptrType:this,ptr:a})}var c=this.getPointee(a);if(!c)return this.destructor(a),null;var d=getInheritedInstance(this.registeredClass,c);if(void 0!==d){if(0===d.$$.count.value)return d.$$.ptr=c,d.$$.smartPtr=a,d.clone();d=d.clone();this.destructor(a);
return d}d=this.registeredClass.getActualType(c);d=registeredPointers[d];if(!d)return b.call(this);d=this.isConst?d.constPointerType:d.pointerType;var e=downcastPointer(c,this.registeredClass,d.registeredClass);return null===e?b.call(this):this.isSmartPointer?makeClassHandle(d.registeredClass.instancePrototype,{ptrType:d,ptr:e,smartPtrType:this,smartPtr:a}):makeClassHandle(d.registeredClass.instancePrototype,{ptrType:d,ptr:e})}
function attachFinalizer(a){if("undefined"===typeof FinalizationRegistry)return attachFinalizer=b=>b,a;finalizationRegistry=new FinalizationRegistry(b=>{releaseClassHandle(b.$$)});attachFinalizer=b=>{var c=b.$$;c.smartPtr&&finalizationRegistry.register(b,{$$:c},b);return b};detachFinalizer=b=>finalizationRegistry.unregister(b);return attachFinalizer(a)}
function ClassHandle_clone(){this.$$.ptr||throwInstanceAlreadyDeleted(this);if(this.$$.preservePointerOnDelete)return this.$$.count.value+=1,this;var a=attachFinalizer(Object.create(Object.getPrototypeOf(this),{$$:{value:shallowCopyInternalPointer(this.$$)}}));a.$$.count.value+=1;a.$$.deleteScheduled=!1;return a}
function ClassHandle_delete(){this.$$.ptr||throwInstanceAlreadyDeleted(this);this.$$.deleteScheduled&&!this.$$.preservePointerOnDelete&&throwBindingError("Object already scheduled for deletion");detachFinalizer(this);releaseClassHandle(this.$$);this.$$.preservePointerOnDelete||(this.$$.smartPtr=void 0,this.$$.ptr=void 0)}function ClassHandle_isDeleted(){return!this.$$.ptr}
function ClassHandle_deleteLater(){this.$$.ptr||throwInstanceAlreadyDeleted(this);this.$$.deleteScheduled&&!this.$$.preservePointerOnDelete&&throwBindingError("Object already scheduled for deletion");deletionQueue.push(this);1===deletionQueue.length&&delayFunction&&delayFunction(flushPendingDeletes);this.$$.deleteScheduled=!0;return this}
function init_ClassHandle(){ClassHandle.prototype.isAliasOf=ClassHandle_isAliasOf;ClassHandle.prototype.clone=ClassHandle_clone;ClassHandle.prototype["delete"]=ClassHandle_delete;ClassHandle.prototype.isDeleted=ClassHandle_isDeleted;ClassHandle.prototype.deleteLater=ClassHandle_deleteLater}function ClassHandle(){}
function ensureOverloadTable(a,b,c){if(void 0===a[b].overloadTable){var d=a[b];a[b]=function(){a[b].overloadTable.hasOwnProperty(arguments.length)||throwBindingError("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].overloadTable+")!");return a[b].overloadTable[arguments.length].apply(this,arguments)};a[b].overloadTable=[];a[b].overloadTable[d.argCount]=d}}
function exposePublicSymbol(a,b,c){Module.hasOwnProperty(a)?((void 0===c||void 0!==Module[a].overloadTable&&void 0!==Module[a].overloadTable[c])&&throwBindingError("Cannot register public name '"+a+"' twice"),ensureOverloadTable(Module,a,a),Module.hasOwnProperty(c)&&throwBindingError("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),Module[a].overloadTable[c]=b):(Module[a]=b,void 0!==c&&(Module[a].numArguments=c))}
function RegisteredClass(a,b,c,d,e,f,k,h){this.name=a;this.constructor=b;this.instancePrototype=c;this.rawDestructor=d;this.baseClass=e;this.getActualType=f;this.upcast=k;this.downcast=h;this.pureVirtualFunctions=[]}function upcastPointer(a,b,c){for(;b!==c;)b.upcast||throwBindingError("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.upcast(a),b=b.baseClass;return a}
function constNoSmartPtrRawPointerToWireType(a,b){if(null===b)return this.isReference&&throwBindingError("null is not a valid "+this.name),0;b.$$||throwBindingError('Cannot pass "'+embindRepr(b)+'" as a '+this.name);b.$$.ptr||throwBindingError("Cannot pass deleted object as a pointer of type "+this.name);return upcastPointer(b.$$.ptr,b.$$.ptrType.registeredClass,this.registeredClass)}
function genericPointerToWireType(a,b){if(null===b){this.isReference&&throwBindingError("null is not a valid "+this.name);if(this.isSmartPointer){var c=this.rawConstructor();null!==a&&a.push(this.rawDestructor,c);return c}return 0}b.$$||throwBindingError('Cannot pass "'+embindRepr(b)+'" as a '+this.name);b.$$.ptr||throwBindingError("Cannot pass deleted object as a pointer of type "+this.name);!this.isConst&&b.$$.ptrType.isConst&&throwBindingError("Cannot convert argument of type "+(b.$$.smartPtrType?
b.$$.smartPtrType.name:b.$$.ptrType.name)+" to parameter type "+this.name);c=upcastPointer(b.$$.ptr,b.$$.ptrType.registeredClass,this.registeredClass);if(this.isSmartPointer)switch(void 0===b.$$.smartPtr&&throwBindingError("Passing raw pointer to smart pointer is illegal"),this.sharingPolicy){case 0:b.$$.smartPtrType===this?c=b.$$.smartPtr:throwBindingError("Cannot convert argument of type "+(b.$$.smartPtrType?b.$$.smartPtrType.name:b.$$.ptrType.name)+" to parameter type "+this.name);break;case 1:c=
b.$$.smartPtr;break;case 2:if(b.$$.smartPtrType===this)c=b.$$.smartPtr;else{var d=b.clone();c=this.rawShare(c,Emval.toHandle(function(){d["delete"]()}));null!==a&&a.push(this.rawDestructor,c)}break;default:throwBindingError("Unsupporting sharing policy")}return c}
function nonConstNoSmartPtrRawPointerToWireType(a,b){if(null===b)return this.isReference&&throwBindingError("null is not a valid "+this.name),0;b.$$||throwBindingError('Cannot pass "'+embindRepr(b)+'" as a '+this.name);b.$$.ptr||throwBindingError("Cannot pass deleted object as a pointer of type "+this.name);b.$$.ptrType.isConst&&throwBindingError("Cannot convert argument of type "+b.$$.ptrType.name+" to parameter type "+this.name);return upcastPointer(b.$$.ptr,b.$$.ptrType.registeredClass,this.registeredClass)}
function simpleReadValueFromPointer(a){return this.fromWireType(HEAP32[a>>2])}function RegisteredPointer_getPointee(a){this.rawGetPointee&&(a=this.rawGetPointee(a));return a}function RegisteredPointer_destructor(a){this.rawDestructor&&this.rawDestructor(a)}function RegisteredPointer_deleteObject(a){if(null!==a)a["delete"]()}
function init_RegisteredPointer(){RegisteredPointer.prototype.getPointee=RegisteredPointer_getPointee;RegisteredPointer.prototype.destructor=RegisteredPointer_destructor;RegisteredPointer.prototype.argPackAdvance=8;RegisteredPointer.prototype.readValueFromPointer=simpleReadValueFromPointer;RegisteredPointer.prototype.deleteObject=RegisteredPointer_deleteObject;RegisteredPointer.prototype.fromWireType=RegisteredPointer_fromWireType}
function RegisteredPointer(a,b,c,d,e,f,k,h,l,m,n){this.name=a;this.registeredClass=b;this.isReference=c;this.isConst=d;this.isSmartPointer=e;this.pointeeType=f;this.sharingPolicy=k;this.rawGetPointee=h;this.rawConstructor=l;this.rawShare=m;this.rawDestructor=n;e||void 0!==b.baseClass?this.toWireType=genericPointerToWireType:(this.toWireType=d?constNoSmartPtrRawPointerToWireType:nonConstNoSmartPtrRawPointerToWireType,this.destructorFunction=null)}
function replacePublicSymbol(a,b,c){Module.hasOwnProperty(a)||throwInternalError("Replacing nonexistant public symbol");void 0!==Module[a].overloadTable&&void 0!==c?Module[a].overloadTable[c]=b:(Module[a]=b,Module[a].argCount=c)}function dynCallLegacy(a,b,c){a=Module["dynCall_"+a];return c&&c.length?a.apply(null,[b].concat(c)):a.call(null,b)}function dynCall(a,b,c){return a.includes("j")?dynCallLegacy(a,b,c):getWasmTableEntry(b).apply(null,c)}
function getDynCaller(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);return dynCall(a,b,c)}}function embind__requireFunction(a,b){a=readLatin1String(a);var c=a.includes("j")?getDynCaller(a,b):getWasmTableEntry(b);"function"!=typeof c&&throwBindingError("unknown function pointer with signature "+a+": "+b);return c}var UnboundTypeError=void 0;function getTypeName(a){a=___getTypeName(a);var b=readLatin1String(a);_free(a);return b}
function throwUnboundTypeError(a,b){function c(f){e[f]||registeredTypes[f]||(typeDependencies[f]?typeDependencies[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new UnboundTypeError(a+": "+d.map(getTypeName).join([", "]));}
function __embind_register_class(a,b,c,d,e,f,k,h,l,m,n,q,r){n=readLatin1String(n);f=embind__requireFunction(e,f);h&&(h=embind__requireFunction(k,h));m&&(m=embind__requireFunction(l,m));r=embind__requireFunction(q,r);var g=makeLegalFunctionName(n);exposePublicSymbol(g,function(){throwUnboundTypeError("Cannot construct "+n+" due to unbound types",[d])});whenDependentTypesAreResolved([a,b,c],d?[d]:[],function(p){p=p[0];if(d){var t=p.registeredClass;var u=t.instancePrototype}else u=ClassHandle.prototype;
p=createNamedFunction(g,function(){if(Object.getPrototypeOf(this)!==v)throw new BindingError("Use 'new' to construct "+n);if(void 0===w.constructor_body)throw new BindingError(n+" has no accessible constructor");var x=w.constructor_body[arguments.length];if(void 0===x)throw new BindingError("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(w.constructor_body).toString()+") parameters instead!");return x.apply(this,arguments)});var v=
Object.create(u,{constructor:{value:p}});p.prototype=v;var w=new RegisteredClass(n,p,v,r,t,f,h,m);t=new RegisteredPointer(n,w,!0,!1,!1);u=new RegisteredPointer(n+"*",w,!1,!1,!1);var y=new RegisteredPointer(n+" const*",w,!1,!0,!1);registeredPointers[a]={pointerType:u,constPointerType:y};replacePublicSymbol(g,p);return[t,u,y]})}
function new_(a,b){if(!(a instanceof Function))throw new TypeError("new_ called with constructor type "+typeof a+" which is not a function");var c=createNamedFunction(a.name||"unknownFunctionName",function(){});c.prototype=a.prototype;c=new c;a=a.apply(c,b);return a instanceof Object?a:c}function runDestructors(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function craftInvokerFunction(a,b,c,d,e){var f=b.length;2>f&&throwBindingError("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,h=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].destructorFunction){h=!0;break}var l="void"!==b[0].name,m="",n="";for(c=0;c<f-2;++c)m+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+makeLegalFunctionName(a)+"("+m+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+
a+" called with ' + arguments.length + ' arguments, expected "+(f-2)+" args!');\n}\n";h&&(a+="var destructors = [];\n");var q=h?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[throwBindingError,d,e,runDestructors,b[0],b[1]];k&&(a+="var thisWired = classParam.toWireType("+q+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+q+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),d.push(b[c+2]);k&&(n="thisWired"+
(0<n.length?", ":"")+n);a+=(l?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(h)a+="runDestructors(destructors);\n";else for(c=k?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].destructorFunction&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",m.push(f+"_dtor"),d.push(b[c].destructorFunction));l&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return new_(Function,m).apply(null,d)}
function heap32VectorToArray(a,b){for(var c=[],d=0;d<a;d++)c.push(HEAPU32[b+4*d>>2]);return c}
function __embind_register_class_class_function(a,b,c,d,e,f,k){var h=heap32VectorToArray(c,d);b=readLatin1String(b);f=embind__requireFunction(e,f);whenDependentTypesAreResolved([],[a],function(l){function m(){throwUnboundTypeError("Cannot call "+n+" due to unbound types",h)}l=l[0];var n=l.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var q=l.registeredClass.constructor;void 0===q[b]?(m.argCount=c-1,q[b]=m):(ensureOverloadTable(q,b,n),q[b].overloadTable[c-1]=m);whenDependentTypesAreResolved([],
h,function(r){r=[r[0],null].concat(r.slice(1));r=craftInvokerFunction(n,r,null,f,k);void 0===q[b].overloadTable?(r.argCount=c-1,q[b]=r):q[b].overloadTable[c-1]=r;return[]});return[]})}
function __embind_register_class_constructor(a,b,c,d,e,f){assert(0<b);var k=heap32VectorToArray(b,c);e=embind__requireFunction(d,e);whenDependentTypesAreResolved([],[a],function(h){h=h[0];var l="constructor "+h.name;void 0===h.registeredClass.constructor_body&&(h.registeredClass.constructor_body=[]);if(void 0!==h.registeredClass.constructor_body[b-1])throw new BindingError("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+h.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
h.registeredClass.constructor_body[b-1]=()=>{throwUnboundTypeError("Cannot construct "+h.name+" due to unbound types",k)};whenDependentTypesAreResolved([],k,function(m){m.splice(1,0,null);h.registeredClass.constructor_body[b-1]=craftInvokerFunction(l,m,null,e,f);return[]});return[]})}
function __embind_register_class_function(a,b,c,d,e,f,k,h){var l=heap32VectorToArray(c,d);b=readLatin1String(b);f=embind__requireFunction(e,f);whenDependentTypesAreResolved([],[a],function(m){function n(){throwUnboundTypeError("Cannot call "+q+" due to unbound types",l)}m=m[0];var q=m.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.registeredClass.pureVirtualFunctions.push(b);var r=m.registeredClass.instancePrototype,g=r[b];void 0===g||void 0===g.overloadTable&&g.className!==m.name&&
g.argCount===c-2?(n.argCount=c-2,n.className=m.name,r[b]=n):(ensureOverloadTable(r,b,q),r[b].overloadTable[c-2]=n);whenDependentTypesAreResolved([],l,function(p){p=craftInvokerFunction(q,p,m,f,k);void 0===r[b].overloadTable?(p.argCount=c-2,r[b]=p):r[b].overloadTable[c-2]=p;return[]});return[]})}var emval_free_list=[],emval_handle_array=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function __emval_decref(a){4<a&&0===--emval_handle_array[a].refcount&&(emval_handle_array[a]=void 0,emval_free_list.push(a))}function count_emval_handles(){for(var a=0,b=5;b<emval_handle_array.length;++b)void 0!==emval_handle_array[b]&&++a;return a}function get_first_emval(){for(var a=5;a<emval_handle_array.length;++a)if(void 0!==emval_handle_array[a])return emval_handle_array[a];return null}
function init_emval(){Module.count_emval_handles=count_emval_handles;Module.get_first_emval=get_first_emval}var Emval={toValue:a=>{a||throwBindingError("Cannot use deleted val. handle = "+a);return emval_handle_array[a].value},toHandle:a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=emval_free_list.length?emval_free_list.pop():emval_handle_array.length;emval_handle_array[b]={refcount:1,value:a};return b}}};
function __embind_register_emval(a,b){b=readLatin1String(b);registerType(a,{name:b,fromWireType:function(c){var d=Emval.toValue(c);__emval_decref(c);return d},toWireType:function(c,d){return Emval.toHandle(d)},argPackAdvance:8,readValueFromPointer:simpleReadValueFromPointer,destructorFunction:null})}function embindRepr(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function floatReadValueFromPointer(a,b){switch(b){case 2:return function(c){return this.fromWireType(HEAPF32[c>>2])};case 3:return function(c){return this.fromWireType(HEAPF64[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function __embind_register_float(a,b,c){c=getShiftFromSize(c);b=readLatin1String(b);registerType(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:floatReadValueFromPointer(b,c),destructorFunction:null})}
function integerReadValueFromPointer(a,b,c){switch(b){case 0:return c?function(d){return HEAP8[d]}:function(d){return HEAPU8[d]};case 1:return c?function(d){return HEAP16[d>>1]}:function(d){return HEAPU16[d>>1]};case 2:return c?function(d){return HEAP32[d>>2]}:function(d){return HEAPU32[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}
function __embind_register_integer(a,b,c,d,e){b=readLatin1String(b);-1===e&&(e=4294967295);e=getShiftFromSize(c);var f=h=>h;if(0===d){var k=32-8*c;f=h=>h<<k>>>k}c=b.includes("unsigned")?function(h,l){return l>>>0}:function(h,l){return l};registerType(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:integerReadValueFromPointer(b,e,0!==d),destructorFunction:null})}
function __embind_register_memory_view(a,b,c){function d(f){f>>=2;var k=HEAPU32;return new e(buffer,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=readLatin1String(c);registerType(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ignoreDuplicateRegistrations:!0})}
function __embind_register_std_string(a,b){b=readLatin1String(b);var c="std::string"===b;registerType(a,{name:b,fromWireType:function(d){var e=HEAPU32[d>>2],f=d+4;if(c)for(var k=f,h=0;h<=e;++h){var l=f+h;if(h==e||0==HEAPU8[l]){k=UTF8ToString(k,l-k);if(void 0===m)var m=k;else m+=String.fromCharCode(0),m+=k;k=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(HEAPU8[f+h]);m=m.join("")}_free(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==
typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||throwBindingError("Cannot pass non-string to std::string");var k=c&&f?lengthBytesUTF8(e):e.length;var h=_malloc(4+k+1),l=h+4;HEAPU32[h>>2]=k;if(c&&f)stringToUTF8(e,l,k+1);else if(f)for(f=0;f<k;++f){var m=e.charCodeAt(f);255<m&&(_free(l),throwBindingError("String has UTF-16 code units that do not fit in 8 bits"));HEAPU8[l+f]=m}else for(f=0;f<k;++f)HEAPU8[l+f]=e[f];null!==d&&d.push(_free,h);return h},argPackAdvance:8,
readValueFromPointer:simpleReadValueFromPointer,destructorFunction:function(d){_free(d)}})}var UTF16Decoder="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function UTF16ToString(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&HEAPU16[c];)++c;c<<=1;if(32<c-a&&UTF16Decoder)return UTF16Decoder.decode(HEAPU8.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=HEAP16[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function stringToUTF16(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);HEAP16[b>>1]=f;b+=2}HEAP16[b>>1]=0;return b-d}function lengthBytesUTF16(a){return 2*a.length}function UTF32ToString(a,b){for(var c=0,d="";!(c>=b/4);){var e=HEAP32[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function stringToUTF32(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}HEAP32[b>>2]=f;b+=4;if(b+4>c)break}HEAP32[b>>2]=0;return b-d}function lengthBytesUTF32(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}
function __embind_register_std_wstring(a,b,c){c=readLatin1String(c);if(2===b){var d=UTF16ToString;var e=stringToUTF16;var f=lengthBytesUTF16;var k=()=>HEAPU16;var h=1}else 4===b&&(d=UTF32ToString,e=stringToUTF32,f=lengthBytesUTF32,k=()=>HEAPU32,h=2);registerType(a,{name:c,fromWireType:function(l){for(var m=HEAPU32[l>>2],n=k(),q,r=l+4,g=0;g<=m;++g){var p=l+4+g*b;if(g==m||0==n[p>>h])r=d(r,p-r),void 0===q?q=r:(q+=String.fromCharCode(0),q+=r),r=p+b}_free(l);return q},toWireType:function(l,m){"string"!=
typeof m&&throwBindingError("Cannot pass non-string to C++ string type "+c);var n=f(m),q=_malloc(4+n+b);HEAPU32[q>>2]=n>>h;e(m,q+4,n+b);null!==l&&l.push(_free,q);return q},argPackAdvance:8,readValueFromPointer:simpleReadValueFromPointer,destructorFunction:function(l){_free(l)}})}function __embind_register_void(a,b){b=readLatin1String(b);registerType(a,{isVoid:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(c,d){}})}var nowIsMonotonic=!0;
function __emscripten_get_now_is_monotonic(){return nowIsMonotonic}function __emval_incref(a){4<a&&(emval_handle_array[a].refcount+=1)}function requireRegisteredType(a,b){var c=registeredTypes[a];void 0===c&&throwBindingError(b+" has unknown type "+getTypeName(a));return c}function __emval_take_value(a,b){a=requireRegisteredType(a,"_emval_take_value");a=a.readValueFromPointer(b);return Emval.toHandle(a)}function readI53FromI64(a){return HEAPU32[a>>2]+4294967296*HEAP32[a+4>>2]}
function __isLeapYear(a){return 0===a%4&&(0!==a%100||0===a%400)}var __MONTH_DAYS_LEAP_CUMULATIVE=[0,31,60,91,121,152,182,213,244,274,305,335],__MONTH_DAYS_REGULAR_CUMULATIVE=[0,31,59,90,120,151,181,212,243,273,304,334];function __yday_from_date(a){return(__isLeapYear(a.getFullYear())?__MONTH_DAYS_LEAP_CUMULATIVE:__MONTH_DAYS_REGULAR_CUMULATIVE)[a.getMonth()]+a.getDate()-1}
function __localtime_js(a,b){a=new Date(1E3*readI53FromI64(a));HEAP32[b>>2]=a.getSeconds();HEAP32[b+4>>2]=a.getMinutes();HEAP32[b+8>>2]=a.getHours();HEAP32[b+12>>2]=a.getDate();HEAP32[b+16>>2]=a.getMonth();HEAP32[b+20>>2]=a.getFullYear()-1900;HEAP32[b+24>>2]=a.getDay();var c=__yday_from_date(a)|0;HEAP32[b+28>>2]=c;HEAP32[b+36>>2]=-(60*a.getTimezoneOffset());var d=new Date(a.getFullYear(),0,1);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();d=d.getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==
Math.min(d,c))|0;HEAP32[b+32>>2]=a}function __mmap_js(a,b,c,d,e,f,k){return-52}function __munmap_js(a,b,c,d,e,f){}function allocateUTF8(a){var b=lengthBytesUTF8(a)+1,c=_malloc(b);c&&stringToUTF8Array(a,HEAP8,c,b);return c}
function __tzset_js(a,b,c){function d(l){return(l=l.toTimeString().match(/\(([A-Za-z ]+)\)$/))?l[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),k=new Date(e,6,1);e=f.getTimezoneOffset();var h=k.getTimezoneOffset();HEAPU32[a>>2]=60*Math.max(e,h);HEAP32[b>>2]=Number(e!=h);a=d(f);b=d(k);a=allocateUTF8(a);b=allocateUTF8(b);h<e?(HEAPU32[c>>2]=a,HEAPU32[c+4>>2]=b):(HEAPU32[c>>2]=b,HEAPU32[c+4>>2]=a)}function _abort(){abort("")}
function handleException(a){if(a instanceof ExitStatus||"unwind"==a)return EXITSTATUS;quit_(1,a)}function callUserCallback(a){if(!ABORT)try{a()}catch(b){handleException(b)}}function _alarm(a){setTimeout(function(){callUserCallback(function(){_raise(14)})},1E3*a)}function _emscripten_date_now(){return Date.now()}var _emscripten_get_now;_emscripten_get_now=()=>performance.now();function _emscripten_memcpy_big(a,b,c){HEAPU8.copyWithin(a,b,b+c)}function abortOnCannotGrowMemory(a){abort("OOM")}
function _emscripten_resize_heap(a){abortOnCannotGrowMemory(a>>>0)}var ENV={};function getExecutableName(){return thisProgram||"./this.program"}
function getEnvStrings(){if(!getEnvStrings.strings){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:getExecutableName()},b;for(b in ENV)void 0===ENV[b]?delete a[b]:a[b]=ENV[b];var c=[];for(b in a)c.push(b+"="+a[b]);getEnvStrings.strings=c}return getEnvStrings.strings}
function writeAsciiToMemory(a,b,c){for(var d=0;d<a.length;++d)HEAP8[b++>>0]=a.charCodeAt(d);c||(HEAP8[b>>0]=0)}function _environ_get(a,b){var c=0;getEnvStrings().forEach(function(d,e){var f=b+c;HEAPU32[a+4*e>>2]=f;writeAsciiToMemory(d,f);c+=d.length+1});return 0}function _environ_sizes_get(a,b){var c=getEnvStrings();HEAPU32[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});HEAPU32[b>>2]=d;return 0}
function _proc_exit(a){EXITSTATUS=a;if(!keepRuntimeAlive()){if(Module.onExit)Module.onExit(a);ABORT=!0}quit_(a,new ExitStatus(a))}function exitJS(a,b){EXITSTATUS=a;_proc_exit(a)}var _exit=exitJS;function _fd_close(a){return 52}function _fd_fdstat_get(a,b){a=1==a||2==a?2:abort();HEAP8[b>>0]=a;return 0}function _fd_pread(a,b,c,d,e,f){return 52}function _fd_read(a,b,c,d){return 52}function _fd_seek(a,b,c,d,e){return 70}var printCharBuffers=[null,[],[]];
function printChar(a,b){var c=printCharBuffers[a];0===b||10===b?((1===a?out:err)(UTF8ArrayToString(c,0)),c.length=0):c.push(b)}function _fd_write(a,b,c,d){for(var e=0,f=0;f<c;f++){var k=HEAPU32[b>>2],h=HEAPU32[b+4>>2];b+=8;for(var l=0;l<h;l++)printChar(a,HEAPU8[k+l]);e+=h}HEAPU32[d>>2]=e;return 0}function __arraySum(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var __MONTH_DAYS_LEAP=[31,29,31,30,31,30,31,31,30,31,30,31],__MONTH_DAYS_REGULAR=[31,28,31,30,31,30,31,31,30,31,30,31];
function __addDays(a,b){for(a=new Date(a.getTime());0<b;){var c=__isLeapYear(a.getFullYear()),d=a.getMonth();c=(c?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR)[d];if(b>c-a.getDate())b-=c-a.getDate()+1,a.setDate(1),11>d?a.setMonth(d+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}function intArrayFromString(a,b,c){c=0<c?c:lengthBytesUTF8(a)+1;c=Array(c);a=stringToUTF8Array(a,c,0,c.length);b&&(c.length=a);return c}
function writeArrayToMemory(a,b){HEAP8.set(a,b)}
function _strftime(a,b,c,d){function e(g,p,t){for(g="number"==typeof g?g.toString():g||"";g.length<p;)g=t[0]+g;return g}function f(g,p){return e(g,p,"0")}function k(g,p){function t(v){return 0>v?-1:0<v?1:0}var u;0===(u=t(g.getFullYear()-p.getFullYear()))&&0===(u=t(g.getMonth()-p.getMonth()))&&(u=t(g.getDate()-p.getDate()));return u}function h(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function l(g){g=__addDays(new Date(g.tm_year+1900,0,1),g.tm_yday);var p=new Date(g.getFullYear(),0,4),t=new Date(g.getFullYear()+1,0,4);p=h(p);t=h(t);return 0>=k(p,g)?0>=k(t,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var m=HEAP32[d+40>>2];d={tm_sec:HEAP32[d>>2],tm_min:HEAP32[d+4>>2],tm_hour:HEAP32[d+8>>2],tm_mday:HEAP32[d+12>>2],tm_mon:HEAP32[d+
16>>2],tm_year:HEAP32[d+20>>2],tm_wday:HEAP32[d+24>>2],tm_yday:HEAP32[d+28>>2],tm_isdst:HEAP32[d+32>>2],tm_gmtoff:HEAP32[d+36>>2],tm_zone:m?UTF8ToString(m):""};c=UTF8ToString(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U",
"%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in m)c=c.replace(new RegExp(n,"g"),m[n]);var q="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");m={"%a":function(g){return q[g.tm_wday].substring(0,3)},"%A":function(g){return q[g.tm_wday]},"%b":function(g){return r[g.tm_mon].substring(0,3)},"%B":function(g){return r[g.tm_mon]},"%C":function(g){return f((g.tm_year+1900)/100|
0,2)},"%d":function(g){return f(g.tm_mday,2)},"%e":function(g){return e(g.tm_mday,2," ")},"%g":function(g){return l(g).toString().substring(2)},"%G":function(g){return l(g)},"%H":function(g){return f(g.tm_hour,2)},"%I":function(g){g=g.tm_hour;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":function(g){return f(g.tm_mday+__arraySum(__isLeapYear(g.tm_year+1900)?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR,g.tm_mon-1),3)},"%m":function(g){return f(g.tm_mon+1,2)},"%M":function(g){return f(g.tm_min,2)},"%n":function(){return"\n"},
"%p":function(g){return 0<=g.tm_hour&&12>g.tm_hour?"AM":"PM"},"%S":function(g){return f(g.tm_sec,2)},"%t":function(){return"\t"},"%u":function(g){return g.tm_wday||7},"%U":function(g){return f(Math.floor((g.tm_yday+7-g.tm_wday)/7),2)},"%V":function(g){var p=Math.floor((g.tm_yday+7-(g.tm_wday+6)%7)/7);2>=(g.tm_wday+371-g.tm_yday-2)%7&&p++;if(p)53==p&&(t=(g.tm_wday+371-g.tm_yday)%7,4==t||3==t&&__isLeapYear(g.tm_year)||(p=1));else{p=52;var t=(g.tm_wday+7-g.tm_yday-1)%7;(4==t||5==t&&__isLeapYear(g.tm_year%
400-1))&&p++}return f(p,2)},"%w":function(g){return g.tm_wday},"%W":function(g){return f(Math.floor((g.tm_yday+7-(g.tm_wday+6)%7)/7),2)},"%y":function(g){return(g.tm_year+1900).toString().substring(2)},"%Y":function(g){return g.tm_year+1900},"%z":function(g){g=g.tm_gmtoff;var p=0<=g;g=Math.abs(g)/60;return(p?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":function(g){return g.tm_zone},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(n in m)c.includes(n)&&(c=c.replace(new RegExp(n,
"g"),m[n](d)));c=c.replace(/\0\0/g,"%");n=intArrayFromString(c,!1);if(n.length>b)return 0;writeArrayToMemory(n,a);return n.length-1}function _strftime_l(a,b,c,d,e){return _strftime(a,b,c,d)}function _wait4(){err("missing function: wait4");abort(-1)}embind_init_charCodes();BindingError=Module.BindingError=extendError(Error,"BindingError");InternalError=Module.InternalError=extendError(Error,"InternalError");init_ClassHandle();init_embind();init_RegisteredPointer();
UnboundTypeError=Module.UnboundTypeError=extendError(Error,"UnboundTypeError");init_emval();
var asmLibraryArg={fa:___call_sighandler,r:___cxa_allocate_exception,t:___cxa_begin_catch,y:___cxa_end_catch,a:___cxa_find_matching_catch_2,j:___cxa_find_matching_catch_3,z:___cxa_free_exception,T:___cxa_rethrow,q:___cxa_throw,ca:___cxa_uncaught_exceptions,e:___resumeException,ua:___syscall_faccessat,oa:___syscall_fstat64,ka:___syscall_getcwd,la:___syscall_lstat64,ma:___syscall_newfstatat,ga:___syscall_openat,ea:___syscall_rmdir,na:___syscall_stat64,L:___syscall_unlinkat,$:__embind_register_bigint,
ya:__embind_register_bool,V:__embind_register_class,Ja:__embind_register_class_class_function,U:__embind_register_class_constructor,s:__embind_register_class_function,xa:__embind_register_emval,Q:__embind_register_float,x:__embind_register_integer,p:__embind_register_memory_view,P:__embind_register_std_string,I:__embind_register_std_wstring,za:__embind_register_void,qa:__emscripten_get_now_is_monotonic,Ga:__emval_decref,Ha:__emval_incref,Ia:__emval_take_value,ra:__localtime_js,ha:__mmap_js,ia:__munmap_js,
sa:__tzset_js,b:_abort,R:_alarm,N:_emscripten_date_now,pa:_emscripten_get_now,ta:_emscripten_memcpy_big,da:_emscripten_resize_heap,va:_environ_get,wa:_environ_sizes_get,S:_exit,O:_fd_close,ja:_fd_fdstat_get,Z:_fd_pread,M:_fd_read,_:_fd_seek,H:_fd_write,Da:invoke_dii,F:invoke_diii,Fa:invoke_fii,G:invoke_fiii,o:invoke_i,d:invoke_ii,Ca:invoke_iidi,Ea:invoke_iifi,c:invoke_iii,g:invoke_iiii,h:invoke_iiiii,v:invoke_iiiiii,m:invoke_iiiiiii,B:invoke_iiiiiiii,E:invoke_iiiiiiiiii,D:invoke_iiiiiiiiiiii,J:invoke_iiiiiiiiiiiii,
aa:invoke_iij,Y:invoke_j,X:invoke_ji,W:invoke_jiiii,l:invoke_v,k:invoke_vi,f:invoke_vii,i:invoke_viii,w:invoke_viiii,K:invoke_viiiii,n:invoke_viiiiii,u:invoke_viiiiiii,A:invoke_viiiiiiiiii,C:invoke_viiiiiiiiiiiiiii,Ba:_strftime,ba:_strftime_l,Aa:_wait4},asm=createWasm(),___wasm_call_ctors=Module.___wasm_call_ctors=function(){return(___wasm_call_ctors=Module.___wasm_call_ctors=Module.asm.La).apply(null,arguments)},_free=Module._free=function(){return(_free=Module._free=Module.asm.Ma).apply(null,arguments)},
_main=Module._main=function(){return(_main=Module._main=Module.asm.Na).apply(null,arguments)},_malloc=Module._malloc=function(){return(_malloc=Module._malloc=Module.asm.Pa).apply(null,arguments)},setTempRet0=Module.setTempRet0=function(){return(setTempRet0=Module.setTempRet0=Module.asm.Qa).apply(null,arguments)},_raise=Module._raise=function(){return(_raise=Module._raise=Module.asm.Ra).apply(null,arguments)},___getTypeName=Module.___getTypeName=function(){return(___getTypeName=Module.___getTypeName=
Module.asm.Sa).apply(null,arguments)},__embind_initialize_bindings=Module.__embind_initialize_bindings=function(){return(__embind_initialize_bindings=Module.__embind_initialize_bindings=Module.asm.Ta).apply(null,arguments)},_setThrew=Module._setThrew=function(){return(_setThrew=Module._setThrew=Module.asm.Ua).apply(null,arguments)},stackSave=Module.stackSave=function(){return(stackSave=Module.stackSave=Module.asm.Va).apply(null,arguments)},stackRestore=Module.stackRestore=function(){return(stackRestore=
Module.stackRestore=Module.asm.Wa).apply(null,arguments)},___cxa_can_catch=Module.___cxa_can_catch=function(){return(___cxa_can_catch=Module.___cxa_can_catch=Module.asm.Xa).apply(null,arguments)},___cxa_is_pointer_type=Module.___cxa_is_pointer_type=function(){return(___cxa_is_pointer_type=Module.___cxa_is_pointer_type=Module.asm.Ya).apply(null,arguments)},dynCall_iij=Module.dynCall_iij=function(){return(dynCall_iij=Module.dynCall_iij=Module.asm.Za).apply(null,arguments)},dynCall_iiij=Module.dynCall_iiij=
function(){return(dynCall_iiij=Module.dynCall_iiij=Module.asm._a).apply(null,arguments)},dynCall_viiiiiji=Module.dynCall_viiiiiji=function(){return(dynCall_viiiiiji=Module.dynCall_viiiiiji=Module.asm.$a).apply(null,arguments)},dynCall_iiiijji=Module.dynCall_iiiijji=function(){return(dynCall_iiiijji=Module.dynCall_iiiijji=Module.asm.ab).apply(null,arguments)},dynCall_iiiiijji=Module.dynCall_iiiiijji=function(){return(dynCall_iiiiijji=Module.dynCall_iiiiijji=Module.asm.bb).apply(null,arguments)},dynCall_viiiij=
Module.dynCall_viiiij=function(){return(dynCall_viiiij=Module.dynCall_viiiij=Module.asm.cb).apply(null,arguments)},dynCall_jiij=Module.dynCall_jiij=function(){return(dynCall_jiij=Module.dynCall_jiij=Module.asm.db).apply(null,arguments)},dynCall_jiii=Module.dynCall_jiii=function(){return(dynCall_jiii=Module.dynCall_jiii=Module.asm.eb).apply(null,arguments)},dynCall_iiiij=Module.dynCall_iiiij=function(){return(dynCall_iiiij=Module.dynCall_iiiij=Module.asm.fb).apply(null,arguments)},dynCall_viiij=Module.dynCall_viiij=
function(){return(dynCall_viiij=Module.dynCall_viiij=Module.asm.gb).apply(null,arguments)},dynCall_iiiiiij=Module.dynCall_iiiiiij=function(){return(dynCall_iiiiiij=Module.dynCall_iiiiiij=Module.asm.hb).apply(null,arguments)},dynCall_iiiiij=Module.dynCall_iiiiij=function(){return(dynCall_iiiiij=Module.dynCall_iiiiij=Module.asm.ib).apply(null,arguments)},dynCall_iiijjii=Module.dynCall_iiijjii=function(){return(dynCall_iiijjii=Module.dynCall_iiijjii=Module.asm.jb).apply(null,arguments)},dynCall_iiiijijii=
Module.dynCall_iiiijijii=function(){return(dynCall_iiiijijii=Module.dynCall_iiiijijii=Module.asm.kb).apply(null,arguments)},dynCall_viiiijiji=Module.dynCall_viiiijiji=function(){return(dynCall_viiiijiji=Module.dynCall_viiiijiji=Module.asm.lb).apply(null,arguments)},dynCall_iiiiijii=Module.dynCall_iiiiijii=function(){return(dynCall_iiiiijii=Module.dynCall_iiiiijii=Module.asm.mb).apply(null,arguments)},dynCall_viijiii=Module.dynCall_viijiii=function(){return(dynCall_viijiii=Module.dynCall_viijiii=Module.asm.nb).apply(null,
arguments)},dynCall_viiiiijii=Module.dynCall_viiiiijii=function(){return(dynCall_viiiiijii=Module.dynCall_viiiiijii=Module.asm.ob).apply(null,arguments)},dynCall_iiiijiii=Module.dynCall_iiiijiii=function(){return(dynCall_iiiijiii=Module.dynCall_iiiijiii=Module.asm.pb).apply(null,arguments)},dynCall_iiijii=Module.dynCall_iiijii=function(){return(dynCall_iiijii=Module.dynCall_iiijii=Module.asm.qb).apply(null,arguments)},dynCall_iiiji=Module.dynCall_iiiji=function(){return(dynCall_iiiji=Module.dynCall_iiiji=
Module.asm.rb).apply(null,arguments)},dynCall_viij=Module.dynCall_viij=function(){return(dynCall_viij=Module.dynCall_viij=Module.asm.sb).apply(null,arguments)},dynCall_viji=Module.dynCall_viji=function(){return(dynCall_viji=Module.dynCall_viji=Module.asm.tb).apply(null,arguments)},dynCall_vijii=Module.dynCall_vijii=function(){return(dynCall_vijii=Module.dynCall_vijii=Module.asm.ub).apply(null,arguments)},dynCall_ji=Module.dynCall_ji=function(){return(dynCall_ji=Module.dynCall_ji=Module.asm.vb).apply(null,
arguments)},dynCall_vij=Module.dynCall_vij=function(){return(dynCall_vij=Module.dynCall_vij=Module.asm.wb).apply(null,arguments)},dynCall_viiiji=Module.dynCall_viiiji=function(){return(dynCall_viiiji=Module.dynCall_viiiji=Module.asm.xb).apply(null,arguments)},dynCall_viijji=Module.dynCall_viijji=function(){return(dynCall_viijji=Module.dynCall_viijji=Module.asm.yb).apply(null,arguments)},dynCall_viiji=Module.dynCall_viiji=function(){return(dynCall_viiji=Module.dynCall_viiji=Module.asm.zb).apply(null,
arguments)},dynCall_viijii=Module.dynCall_viijii=function(){return(dynCall_viijii=Module.dynCall_viijii=Module.asm.Ab).apply(null,arguments)},dynCall_viiijii=Module.dynCall_viiijii=function(){return(dynCall_viiijii=Module.dynCall_viiijii=Module.asm.Bb).apply(null,arguments)},dynCall_vijjii=Module.dynCall_vijjii=function(){return(dynCall_vijjii=Module.dynCall_vijjii=Module.asm.Cb).apply(null,arguments)},dynCall_vijj=Module.dynCall_vijj=function(){return(dynCall_vijj=Module.dynCall_vijj=Module.asm.Db).apply(null,
arguments)},dynCall_vijjj=Module.dynCall_vijjj=function(){return(dynCall_vijjj=Module.dynCall_vijjj=Module.asm.Eb).apply(null,arguments)},dynCall_vijjjji=Module.dynCall_vijjjji=function(){return(dynCall_vijjjji=Module.dynCall_vijjjji=Module.asm.Fb).apply(null,arguments)},dynCall_vijiii=Module.dynCall_vijiii=function(){return(dynCall_vijiii=Module.dynCall_vijiii=Module.asm.Gb).apply(null,arguments)},dynCall_jiji=Module.dynCall_jiji=function(){return(dynCall_jiji=Module.dynCall_jiji=Module.asm.Hb).apply(null,
arguments)},dynCall_j=Module.dynCall_j=function(){return(dynCall_j=Module.dynCall_j=Module.asm.Ib).apply(null,arguments)},dynCall_jiiii=Module.dynCall_jiiii=function(){return(dynCall_jiiii=Module.dynCall_jiiii=Module.asm.Jb).apply(null,arguments)},dynCall_iiiiijj=Module.dynCall_iiiiijj=function(){return(dynCall_iiiiijj=Module.dynCall_iiiiijj=Module.asm.Kb).apply(null,arguments)},dynCall_iiiiiijj=Module.dynCall_iiiiiijj=function(){return(dynCall_iiiiiijj=Module.dynCall_iiiiiijj=Module.asm.Lb).apply(null,
arguments)};function invoke_iii(a,b,c){var d=stackSave();try{return getWasmTableEntry(a)(b,c)}catch(e){stackRestore(d);if(e!==e+0)throw e;_setThrew(1,0)}}function invoke_viiii(a,b,c,d,e){var f=stackSave();try{getWasmTableEntry(a)(b,c,d,e)}catch(k){stackRestore(f);if(k!==k+0)throw k;_setThrew(1,0)}}function invoke_ii(a,b){var c=stackSave();try{return getWasmTableEntry(a)(b)}catch(d){stackRestore(c);if(d!==d+0)throw d;_setThrew(1,0)}}
function invoke_iiii(a,b,c,d){var e=stackSave();try{return getWasmTableEntry(a)(b,c,d)}catch(f){stackRestore(e);if(f!==f+0)throw f;_setThrew(1,0)}}function invoke_vii(a,b,c){var d=stackSave();try{getWasmTableEntry(a)(b,c)}catch(e){stackRestore(d);if(e!==e+0)throw e;_setThrew(1,0)}}function invoke_vi(a,b){var c=stackSave();try{getWasmTableEntry(a)(b)}catch(d){stackRestore(c);if(d!==d+0)throw d;_setThrew(1,0)}}
function invoke_iiiiiii(a,b,c,d,e,f,k){var h=stackSave();try{return getWasmTableEntry(a)(b,c,d,e,f,k)}catch(l){stackRestore(h);if(l!==l+0)throw l;_setThrew(1,0)}}function invoke_v(a){var b=stackSave();try{getWasmTableEntry(a)()}catch(c){stackRestore(b);if(c!==c+0)throw c;_setThrew(1,0)}}function invoke_viii(a,b,c,d){var e=stackSave();try{getWasmTableEntry(a)(b,c,d)}catch(f){stackRestore(e);if(f!==f+0)throw f;_setThrew(1,0)}}
function invoke_iiiiii(a,b,c,d,e,f){var k=stackSave();try{return getWasmTableEntry(a)(b,c,d,e,f)}catch(h){stackRestore(k);if(h!==h+0)throw h;_setThrew(1,0)}}function invoke_iiiii(a,b,c,d,e){var f=stackSave();try{return getWasmTableEntry(a)(b,c,d,e)}catch(k){stackRestore(f);if(k!==k+0)throw k;_setThrew(1,0)}}function invoke_viiiiii(a,b,c,d,e,f,k){var h=stackSave();try{getWasmTableEntry(a)(b,c,d,e,f,k)}catch(l){stackRestore(h);if(l!==l+0)throw l;_setThrew(1,0)}}
function invoke_fii(a,b,c){var d=stackSave();try{return getWasmTableEntry(a)(b,c)}catch(e){stackRestore(d);if(e!==e+0)throw e;_setThrew(1,0)}}function invoke_iifi(a,b,c,d){var e=stackSave();try{return getWasmTableEntry(a)(b,c,d)}catch(f){stackRestore(e);if(f!==f+0)throw f;_setThrew(1,0)}}function invoke_dii(a,b,c){var d=stackSave();try{return getWasmTableEntry(a)(b,c)}catch(e){stackRestore(d);if(e!==e+0)throw e;_setThrew(1,0)}}
function invoke_iidi(a,b,c,d){var e=stackSave();try{return getWasmTableEntry(a)(b,c,d)}catch(f){stackRestore(e);if(f!==f+0)throw f;_setThrew(1,0)}}function invoke_viiiii(a,b,c,d,e,f){var k=stackSave();try{getWasmTableEntry(a)(b,c,d,e,f)}catch(h){stackRestore(k);if(h!==h+0)throw h;_setThrew(1,0)}}function invoke_iiiiiiiiii(a,b,c,d,e,f,k,h,l,m){var n=stackSave();try{return getWasmTableEntry(a)(b,c,d,e,f,k,h,l,m)}catch(q){stackRestore(n);if(q!==q+0)throw q;_setThrew(1,0)}}
function invoke_iiiiiiiiiiiii(a,b,c,d,e,f,k,h,l,m,n,q,r){var g=stackSave();try{return getWasmTableEntry(a)(b,c,d,e,f,k,h,l,m,n,q,r)}catch(p){stackRestore(g);if(p!==p+0)throw p;_setThrew(1,0)}}function invoke_iiiiiiii(a,b,c,d,e,f,k,h){var l=stackSave();try{return getWasmTableEntry(a)(b,c,d,e,f,k,h)}catch(m){stackRestore(l);if(m!==m+0)throw m;_setThrew(1,0)}}function invoke_i(a){var b=stackSave();try{return getWasmTableEntry(a)()}catch(c){stackRestore(b);if(c!==c+0)throw c;_setThrew(1,0)}}
function invoke_fiii(a,b,c,d){var e=stackSave();try{return getWasmTableEntry(a)(b,c,d)}catch(f){stackRestore(e);if(f!==f+0)throw f;_setThrew(1,0)}}function invoke_diii(a,b,c,d){var e=stackSave();try{return getWasmTableEntry(a)(b,c,d)}catch(f){stackRestore(e);if(f!==f+0)throw f;_setThrew(1,0)}}function invoke_viiiiiii(a,b,c,d,e,f,k,h){var l=stackSave();try{getWasmTableEntry(a)(b,c,d,e,f,k,h)}catch(m){stackRestore(l);if(m!==m+0)throw m;_setThrew(1,0)}}
function invoke_iiiiiiiiiiii(a,b,c,d,e,f,k,h,l,m,n,q){var r=stackSave();try{return getWasmTableEntry(a)(b,c,d,e,f,k,h,l,m,n,q)}catch(g){stackRestore(r);if(g!==g+0)throw g;_setThrew(1,0)}}function invoke_viiiiiiiiii(a,b,c,d,e,f,k,h,l,m,n){var q=stackSave();try{getWasmTableEntry(a)(b,c,d,e,f,k,h,l,m,n)}catch(r){stackRestore(q);if(r!==r+0)throw r;_setThrew(1,0)}}
function invoke_viiiiiiiiiiiiiii(a,b,c,d,e,f,k,h,l,m,n,q,r,g,p,t){var u=stackSave();try{getWasmTableEntry(a)(b,c,d,e,f,k,h,l,m,n,q,r,g,p,t)}catch(v){stackRestore(u);if(v!==v+0)throw v;_setThrew(1,0)}}function invoke_iij(a,b,c,d){var e=stackSave();try{return dynCall_iij(a,b,c,d)}catch(f){stackRestore(e);if(f!==f+0)throw f;_setThrew(1,0)}}function invoke_j(a){var b=stackSave();try{return dynCall_j(a)}catch(c){stackRestore(b);if(c!==c+0)throw c;_setThrew(1,0)}}
function invoke_ji(a,b){var c=stackSave();try{return dynCall_ji(a,b)}catch(d){stackRestore(c);if(d!==d+0)throw d;_setThrew(1,0)}}function invoke_jiiii(a,b,c,d,e){var f=stackSave();try{return dynCall_jiiii(a,b,c,d,e)}catch(k){stackRestore(f);if(k!==k+0)throw k;_setThrew(1,0)}}var calledRun;dependenciesFulfilled=function runCaller(){calledRun||run();calledRun||(dependenciesFulfilled=runCaller)};
function callMain(a){a=Module._main;try{var b=a(0,0);exitJS(b,!0);return b}catch(c){return handleException(c)}}
function run(a){function b(){if(!calledRun&&(calledRun=!0,Module.calledRun=!0,!ABORT)){initRuntime();preMain();readyPromiseResolve(Module);if(Module.onRuntimeInitialized)Module.onRuntimeInitialized();shouldRunNow&&callMain(a);postRun()}}a=a||arguments_;0<runDependencies||(preRun(),0<runDependencies||(Module.setStatus?(Module.setStatus("Running..."),setTimeout(function(){setTimeout(function(){Module.setStatus("")},1);b()},1)):b()))}
if(Module.preInit)for("function"==typeof Module.preInit&&(Module.preInit=[Module.preInit]);0<Module.preInit.length;)Module.preInit.pop()();var shouldRunNow=!0;Module.noInitialRun&&(shouldRunNow=!1);run();


  return createGlobalModule.ready
}
);
})();
export default createGlobalModule;