
var createGlobalModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createGlobalModule) {
  createGlobalModule = createGlobalModule || {};


var f;f||(f=typeof createGlobalModule !== 'undefined' ? createGlobalModule : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},f),da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,p="",ja,ka,la;
if(ia){p=ha?require("path").dirname(p)+"/":__dirname+"/";var fs,ma;"function"===typeof require&&(fs=require("fs"),ma=require("path"));ja=(a,b)=>{a=ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};la=a=>{a=ja(a,!0);a.buffer||(a=new Uint8Array(a));return a};ka=(a,b,c)=>{a=ma.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;
});process.on("unhandledRejection",function(a){throw a;});ea=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof oa||t("exiting due to exception: "+b);process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(fa||ha)ha?p=self.location.href:"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src),_scriptDir&&(p=_scriptDir),0!==p.indexOf("blob:")?p=p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):p="",ja=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var pa=f.print||console.log.bind(console),t=f.printErr||console.warn.bind(console);Object.assign(f,ca);ca=null;
f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);var qa;f.wasmBinary&&(qa=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&w("no native wasm support detected");var ra,sa=!1,ta="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function x(a,b){return a?ua(y,a,b):""}
function va(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var xa,z,y,ya,za,A,B,Aa,Ba,Ca,Da=[],Ea=[],Fa=[],Ga=[];function Ha(){var a=f.preRun.shift();Da.unshift(a)}var Ia=0,Ja=null,Ka=null;function w(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";t(a);sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}
function La(){return C.startsWith("data:application/octet-stream;base64,")}var C;C="VIRELANG.wasm";if(!La()){var Ma=C;C=f.locateFile?f.locateFile(Ma,p):p+Ma}function Na(){var a=C;try{if(a==C&&qa)return new Uint8Array(qa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}
function Oa(){if(!qa&&(fa||ha)){if("function"==typeof fetch&&!C.startsWith("file://"))return fetch(C,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+C+"'";return a.arrayBuffer()}).catch(function(){return Na()});if(ka)return new Promise(function(a,b){ka(C,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Na()})}var E,F;
function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Pa(a){for(;0<a.length;)a.shift()(f)}function H(a){return Ca.get(a)}var Qa=[],Ra=0,Sa=0;
function Ta(a){this.tc=a;this.Pb=a-24;this.cd=function(b){B[this.Pb+4>>2]=b};this.hc=function(){return B[this.Pb+4>>2]};this.ad=function(b){B[this.Pb+8>>2]=b};this.md=function(){return B[this.Pb+8>>2]};this.bd=function(){A[this.Pb>>2]=0};this.Kc=function(b){z[this.Pb+12>>0]=b?1:0};this.Yc=function(){return 0!=z[this.Pb+12>>0]};this.Lc=function(b){z[this.Pb+13>>0]=b?1:0};this.Tc=function(){return 0!=z[this.Pb+13>>0]};this.$c=function(b,c){this.Ec(0);this.cd(b);this.ad(c);this.bd();this.Kc(!1);this.Lc(!1)};
this.Wc=function(){A[this.Pb>>2]+=1};this.td=function(){var b=A[this.Pb>>2];A[this.Pb>>2]=b-1;return 1===b};this.Ec=function(b){B[this.Pb+16>>2]=b};this.Xc=function(){return B[this.Pb+16>>2]};this.Zc=function(){if(Ua(this.hc()))return B[this.tc>>2];var b=this.Xc();return 0!==b?b:this.tc}}function Va(a){try{return I((new Ta(a)).Pb)}catch(b){}}
var Wa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Xa=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Wa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ya=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Za=a=>
{if("/"===a)return"/";a=Xa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function $a(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return()=>b.randomBytes(1)[0]}catch(c){}return()=>w("randomDevice")}
function ab(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Wa(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function bb(a,b){var c=Array(wa(a)+1);a=va(a,c,0,c.length);b&&(c.length=a);return c}var cb=[];function db(a,b){cb[a]={input:[],output:[],sc:b};eb(a,fb)}
var fb={open:function(a){var b=cb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.sc.fsync(a.tty)},fsync:function(a){a.tty.sc.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.sc.Sc)throw new J(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.sc.Sc(a.tty)}catch(l){throw new J(29);}if(void 0===h&&0===e)throw new J(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.sc.Hc)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.sc.Hc(a.tty,b[c+e])}catch(g){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},gb={Sc:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=bb(b,!0)}return a.input.shift()},Hc:function(a,b){null===b||10===b?(pa(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(pa(ua(a.output,0)),a.output=[])}},hb={Hc:function(a,b){null===b||10===b?(t(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(t(ua(a.output,0)),a.output=[])}},L={bc:null,fc:function(){return L.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);L.bc||(L.bc={dir:{node:{ac:L.Qb.ac,cc:L.Qb.cc,lookup:L.Qb.lookup,zc:L.Qb.zc,rename:L.Qb.rename,unlink:L.Qb.unlink,rmdir:L.Qb.rmdir,readdir:L.Qb.readdir,symlink:L.Qb.symlink},stream:{jc:L.Rb.jc}},file:{node:{ac:L.Qb.ac,cc:L.Qb.cc},stream:{jc:L.Rb.jc,read:L.Rb.read,write:L.Rb.write,Nc:L.Rb.Nc,Ac:L.Rb.Ac,Bc:L.Rb.Bc}},link:{node:{ac:L.Qb.ac,cc:L.Qb.cc,readlink:L.Qb.readlink},stream:{}},Oc:{node:{ac:L.Qb.ac,cc:L.Qb.cc},
stream:ib}});c=jb(a,b,c,d);16384===(c.mode&61440)?(c.Qb=L.bc.dir.node,c.Rb=L.bc.dir.stream,c.Sb={}):32768===(c.mode&61440)?(c.Qb=L.bc.file.node,c.Rb=L.bc.file.stream,c.Ub=0,c.Sb=null):40960===(c.mode&61440)?(c.Qb=L.bc.link.node,c.Rb=L.bc.link.stream):8192===(c.mode&61440)&&(c.Qb=L.bc.Oc.node,c.Rb=L.bc.Oc.stream);c.timestamp=Date.now();a&&(a.Sb[b]=c,a.timestamp=c.timestamp);return c},Cd:function(a){return a.Sb?a.Sb.subarray?a.Sb.subarray(0,a.Ub):new Uint8Array(a.Sb):new Uint8Array(0)},Qc:function(a,
b){var c=a.Sb?a.Sb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Sb,a.Sb=new Uint8Array(b),0<a.Ub&&a.Sb.set(c.subarray(0,a.Ub),0))},ud:function(a,b){if(a.Ub!=b)if(0==b)a.Sb=null,a.Ub=0;else{var c=a.Sb;a.Sb=new Uint8Array(b);c&&a.Sb.set(c.subarray(0,Math.min(b,a.Ub)));a.Ub=b}},Qb:{ac:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?
b.size=a.Ub:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ed=4096;b.blocks=Math.ceil(b.size/b.ed);return b},cc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&L.ud(a,b.size)},lookup:function(){throw kb[44];},zc:function(a,b,c,d){return L.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=lb(b,c)}catch(g){}if(d)for(var e in d.Sb)throw new J(55);
}delete a.parent.Sb[a.name];a.parent.timestamp=Date.now();a.name=c;b.Sb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Sb[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=lb(a,b),d;for(d in c.Sb)throw new J(55);delete a.Sb[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Sb)a.Sb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);
return a.link}},Rb:{read:function(a,b,c,d,e){var g=a.node.Sb;if(e>=a.node.Ub)return 0;a=Math.min(a.node.Ub-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Sb||a.Sb.subarray)){if(g)return a.Sb=b.subarray(c,c+d),a.Ub=d;if(0===a.Ub&&0===e)return a.Sb=b.slice(c,c+d),a.Ub=d;if(e+d<=a.Ub)return a.Sb.set(b.subarray(c,c+d),e),d}L.Qc(a,e+d);if(a.Sb.subarray&&b.subarray)a.Sb.set(b.subarray(c,
c+d),e);else for(g=0;g<d;g++)a.Sb[e+g]=b[c+g];a.Ub=Math.max(a.Ub,e+d);return d},jc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ub);if(0>b)throw new J(28);return b},Nc:function(a,b,c){L.Qc(a.node,b+c);a.node.Ub=Math.max(a.node.Ub,b+c)},Ac:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.Sb;if(e&2||a.buffer!==xa){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=65536*Math.ceil(b/65536);
(e=mb(65536,b))?(y.fill(0,e,e+b),b=e):b=0;if(!b)throw new J(48);z.set(a,b)}else c=!1,b=a.byteOffset;return{Pb:b,dd:c}},Bc:function(a,b,c,d){L.Rb.write(a,b,0,d,c,!1);return 0}}},nb=null,ob={},pb=[],qb=1,M=null,rb=!0,J=null,kb={},N=(a,b={})=>{a=ab("/",a);if(!a)return{path:"",node:null};b=Object.assign({Rc:!0,Ic:0},b);if(8<b.Ic)throw new J(32);a=Wa(a.split("/").filter(h=>!!h),!1);for(var c=nb,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=lb(c,a[e]);d=Xa(d+"/"+a[e]);c.qc&&(!g||
g&&b.Rc)&&(c=c.qc.root);if(!g||b.wc)for(g=0;40960===(c.mode&61440);)if(c=sb(d),d=ab(Ya(d),c),c=N(d,{Ic:b.Ic+1}).node,40<g++)throw new J(32);}return{path:d,node:c}},tb=a=>{for(var b;;){if(a===a.parent)return a=a.fc.Uc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},ub=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%M.length},vb=a=>{var b=ub(a.parent.id,a.name);if(M[b]===a)M[b]=a.rc;else for(b=M[b];b;){if(b.rc===a){b.rc=a.rc;break}b=b.rc}},
lb=(a,b)=>{var c;if(c=(c=wb(a,"x"))?c:a.Qb.lookup?0:2)throw new J(c,a);for(c=M[ub(a.id,b)];c;c=c.rc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Qb.lookup(a,b)},jb=(a,b,c,d)=>{a=new xb(a,b,c,d);b=ub(a.parent.id,a.name);a.rc=M[b];return M[b]=a},yb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},zb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},wb=(a,b)=>{if(rb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;
return 0},Ab=(a,b)=>{try{return lb(a,b),20}catch(c){}return wb(a,"wx")},Bb=(a,b,c)=>{try{var d=lb(a,b)}catch(e){return e.Vb}if(a=wb(a,"wx"))return a;if(c){if(16384!==(d.mode&61440))return 54;if(d===d.parent||"/"===tb(d))return 10}else if(16384===(d.mode&61440))return 31;return 0},Cb=()=>{for(var a=0;4096>=a;a++)if(!pb[a])return a;throw new J(33);},Eb=a=>{Db||(Db=function(){this.hc={}},Db.prototype={},Object.defineProperties(Db.prototype,{object:{get:function(){return this.node},set:function(c){this.node=
c}},flags:{get:function(){return this.hc.flags},set:function(c){this.hc.flags=c}},position:{get:function(){return this.hc.position},set:function(c){this.hc.position=c}}}));a=Object.assign(new Db,a);var b=Cb();a.fd=b;return pb[b]=a},ib={open:a=>{a.Rb=ob[a.node.rdev].Rb;a.Rb.open&&a.Rb.open(a)},jc:()=>{throw new J(70);}},eb=(a,b)=>{ob[a]={Rb:b}},Fb=(a,b)=>{var c="/"===b,d=!b;if(c&&nb)throw new J(10);if(!c&&!d){var e=N(b,{Rc:!1});b=e.path;e=e.node;if(e.qc)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);
}b={type:a,Ed:{},Uc:b,od:[]};a=a.fc(b);a.fc=b;b.root=a;c?nb=a:e&&(e.qc=b,e.fc&&e.fc.od.push(b))},O=(a,b,c)=>{var d=N(a,{parent:!0}).node;a=Za(a);if(!a||"."===a||".."===a)throw new J(28);var e=Ab(d,a);if(e)throw new J(e);if(!d.Qb.zc)throw new J(63);return d.Qb.zc(d,a,b,c)},Gb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);O(a,b|8192,c)},Hb=(a,b)=>{if(!ab(a))throw new J(44);var c=N(b,{parent:!0}).node;if(!c)throw new J(44);b=Za(b);var d=Ab(c,b);if(d)throw new J(d);if(!c.Qb.symlink)throw new J(63);c.Qb.symlink(c,
b,a)},Ib=a=>{var b=N(a,{parent:!0}).node;a=Za(a);var c=lb(b,a),d=Bb(b,a,!0);if(d)throw new J(d);if(!b.Qb.rmdir)throw new J(63);if(c.qc)throw new J(10);b.Qb.rmdir(b,a);vb(c)},sb=a=>{a=N(a).node;if(!a)throw new J(44);if(!a.Qb.readlink)throw new J(28);return ab(tb(a.parent),a.Qb.readlink(a))},Jb=(a,b)=>{a=N(a,{wc:!b}).node;if(!a)throw new J(44);if(!a.Qb.ac)throw new J(63);return a.Qb.ac(a)},Kb=a=>Jb(a,!0),Mb=(a,b,c)=>{if(""===a)throw new J(44);if("string"==typeof b){var d=yb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+
b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Xa(a);try{e=N(a,{wc:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new J(20);}else e=O(a,c,0),d=!0;if(!e)throw new J(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new J(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==zb(b)||b&512)?31:wb(e,zb(b)):44))throw new J(c);if(b&512&&!d){c=e;c="string"==typeof c?N(c,{wc:!0}).node:c;if(!c.Qb.cc)throw new J(63);
if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(d=wb(c,"w"))throw new J(d);c.Qb.cc(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Eb({node:e,path:tb(e),flags:b,seekable:!0,position:0,Rb:e.Rb,Bd:[],error:!1});e.Rb.open&&e.Rb.open(e);!f.logReadFiles||b&1||(Lb||(Lb={}),a in Lb||(Lb[a]=1));return e},Nb=(a,b,c)=>{if(null===a.fd)throw new J(8);if(!a.seekable||!a.Rb.jc)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.Rb.jc(a,b,c);a.Bd=[]},Ob=()=>{J||
(J=function(a,b){this.node=b;this.vd=function(c){this.Vb=c};this.vd(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(a=>{kb[a]=new J(a);kb[a].stack="<generic error, no stack>"}))},Pb,Qb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Sb=(a,b,c)=>{a=Xa("/dev/"+a);var d=Qb(!!b,!!c);Rb||(Rb=64);var e=Rb++<<8|0;eb(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,h,l,m)=>{for(var n=0,q=0;q<m;q++){try{var r=b()}catch(v){throw new J(29);
}if(void 0===r&&0===n)throw new J(6);if(null===r||void 0===r)break;n++;h[l+q]=r}n&&(g.node.timestamp=Date.now());return n},write:(g,h,l,m)=>{for(var n=0;n<m;n++)try{c(h[l+n])}catch(q){throw new J(29);}m&&(g.node.timestamp=Date.now());return n}});Gb(a,d,e)},Rb,P={},Db,Lb;function Tb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Q(a).path;if(0==b.length){if(!c)throw new J(44);return a}return Xa(a+"/"+b)}
function Ub(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&Xa(b)!==Xa(tb(e.node)))return-54;throw e;}A[c>>2]=d.dev;A[c+8>>2]=d.ino;A[c+12>>2]=d.mode;B[c+16>>2]=d.nlink;A[c+20>>2]=d.uid;A[c+24>>2]=d.gid;A[c+28>>2]=d.rdev;F=[d.size>>>0,(E=d.size,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];A[c+40>>2]=F[0];A[c+44>>2]=F[1];A[c+48>>2]=4096;A[c+52>>2]=d.blocks;F=[Math.floor(d.atime.getTime()/1E3)>>>0,(E=Math.floor(d.atime.getTime()/
1E3),1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];A[c+56>>2]=F[0];A[c+60>>2]=F[1];B[c+64>>2]=0;F=[Math.floor(d.mtime.getTime()/1E3)>>>0,(E=Math.floor(d.mtime.getTime()/1E3),1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];A[c+72>>2]=F[0];A[c+76>>2]=F[1];B[c+80>>2]=0;F=[Math.floor(d.ctime.getTime()/1E3)>>>0,(E=Math.floor(d.ctime.getTime()/1E3),1<=+Math.abs(E)?
0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];A[c+88>>2]=F[0];A[c+92>>2]=F[1];B[c+96>>2]=0;F=[d.ino>>>0,(E=d.ino,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];A[c+104>>2]=F[0];A[c+108>>2]=F[1];return 0}var Vb=void 0;function Q(a){a=pb[a];if(!a)throw new J(8);return a}
function Wb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Xb=void 0;function R(a){for(var b="";y[a];)b+=Xb[y[a++]];return b}var Yb={},Zb={},$b={};function ac(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function bc(a,b){a=ac(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function cc(a){var b=Error,c=bc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var dc=void 0;function S(a){throw new dc(a);}var ec=void 0;function fc(a){throw new ec(a);}function gc(a,b,c){function d(l){l=c(l);l.length!==a.length&&fc("Mismatched type converter count");for(var m=0;m<a.length;++m)T(a[m],l[m])}a.forEach(function(l){$b[l]=b});var e=Array(b.length),g=[],h=0;b.forEach((l,m)=>{Zb.hasOwnProperty(l)?e[m]=Zb[l]:(g.push(l),Yb.hasOwnProperty(l)||(Yb[l]=[]),Yb[l].push(()=>{e[m]=Zb[l];++h;h===g.length&&d(e)}))});0===g.length&&d(e)}
function T(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(Zb.hasOwnProperty(a)){if(c.nd)return;S("Cannot register type '"+d+"' twice")}Zb[a]=b;delete $b[a];Yb.hasOwnProperty(a)&&(b=Yb[a],delete Yb[a],b.forEach(e=>e()))}function hc(a){S(a.Ob.Wb.Tb.name+" instance already deleted")}var ic=!1;function jc(){}
function kc(a){--a.count.value;0===a.count.value&&(a.Yb?a.Zb.kc(a.Yb):a.Wb.Tb.kc(a.Pb))}function lc(a,b,c){if(b===c)return a;if(void 0===c.$b)return null;a=lc(a,b,c.$b);return null===a?null:c.jd(a)}var mc={},nc=[];function oc(){for(;nc.length;){var a=nc.pop();a.Ob.oc=!1;a["delete"]()}}var pc=void 0,qc={};function rc(a,b){for(void 0===b&&S("ptr should not be undefined");a.$b;)b=a.vc(b),a=a.$b;return qc[b]}
function sc(a,b){b.Wb&&b.Pb||fc("makeClassHandle requires ptr and ptrType");!!b.Zb!==!!b.Yb&&fc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return tc(Object.create(a,{Ob:{value:b}}))}function tc(a){if("undefined"===typeof FinalizationRegistry)return tc=b=>b,a;ic=new FinalizationRegistry(b=>{kc(b.Ob)});tc=b=>{var c=b.Ob;c.Yb&&ic.register(b,{Ob:c},b);return b};jc=b=>{ic.unregister(b)};return tc(a)}function uc(){}
function vc(a,b,c){if(void 0===a[b].Xb){var d=a[b];a[b]=function(){a[b].Xb.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Xb+")!");return a[b].Xb[arguments.length].apply(this,arguments)};a[b].Xb=[];a[b].Xb[d.nc]=d}}
function wc(a,b){f.hasOwnProperty(a)?(S("Cannot register public name '"+a+"' twice"),vc(f,a,a),f.hasOwnProperty(void 0)&&S("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),f[a].Xb[void 0]=b):f[a]=b}function xc(a,b,c,d,e,g,h,l){this.name=a;this.constructor=b;this.pc=c;this.kc=d;this.$b=e;this.kd=g;this.vc=h;this.jd=l;this.qd=[]}
function yc(a,b,c){for(;b!==c;)b.vc||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.vc(a),b=b.$b;return a}function zc(a,b){if(null===b)return this.Gc&&S("null is not a valid "+this.name),0;b.Ob||S('Cannot pass "'+Ac(b)+'" as a '+this.name);b.Ob.Pb||S("Cannot pass deleted object as a pointer of type "+this.name);return yc(b.Ob.Pb,b.Ob.Wb.Tb,this.Tb)}
function Bc(a,b){if(null===b){this.Gc&&S("null is not a valid "+this.name);if(this.yc){var c=this.rd();null!==a&&a.push(this.kc,c);return c}return 0}b.Ob||S('Cannot pass "'+Ac(b)+'" as a '+this.name);b.Ob.Pb||S("Cannot pass deleted object as a pointer of type "+this.name);!this.xc&&b.Ob.Wb.xc&&S("Cannot convert argument of type "+(b.Ob.Zb?b.Ob.Zb.name:b.Ob.Wb.name)+" to parameter type "+this.name);c=yc(b.Ob.Pb,b.Ob.Wb.Tb,this.Tb);if(this.yc)switch(void 0===b.Ob.Yb&&S("Passing raw pointer to smart pointer is illegal"),
this.wd){case 0:b.Ob.Zb===this?c=b.Ob.Yb:S("Cannot convert argument of type "+(b.Ob.Zb?b.Ob.Zb.name:b.Ob.Wb.name)+" to parameter type "+this.name);break;case 1:c=b.Ob.Yb;break;case 2:if(b.Ob.Zb===this)c=b.Ob.Yb;else{var d=b.clone();c=this.sd(c,Cc(function(){d["delete"]()}));null!==a&&a.push(this.kc,c)}break;default:S("Unsupporting sharing policy")}return c}
function Dc(a,b){if(null===b)return this.Gc&&S("null is not a valid "+this.name),0;b.Ob||S('Cannot pass "'+Ac(b)+'" as a '+this.name);b.Ob.Pb||S("Cannot pass deleted object as a pointer of type "+this.name);b.Ob.Wb.xc&&S("Cannot convert argument of type "+b.Ob.Wb.name+" to parameter type "+this.name);return yc(b.Ob.Pb,b.Ob.Wb.Tb,this.Tb)}function Ec(a){return this.fromWireType(A[a>>2])}
function U(a,b,c,d){this.name=a;this.Tb=b;this.Gc=c;this.xc=d;this.yc=!1;this.kc=this.sd=this.rd=this.Vc=this.wd=this.pd=void 0;void 0!==b.$b?this.toWireType=Bc:(this.toWireType=d?zc:Dc,this.ec=null)}function Fc(a,b){f.hasOwnProperty(a)||fc("Replacing nonexistant public symbol");f[a]=b;f[a].nc=void 0}
function Gc(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=f["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=H(b).apply(null,c);return d}}function Hc(a,b){a=R(a);var c=a.includes("j")?Gc(a,b):H(b);"function"!=typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Ic=void 0;function Jc(a){a=Kc(a);var b=R(a);I(a);return b}
function Lc(a,b){function c(g){e[g]||Zb[g]||($b[g]?$b[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Ic(a+": "+d.map(Jc).join([", "]));}function Mc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=bc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Nc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Qc(a,b,c,d,e){var g=b.length;2>g&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ec){l=!0;break}var m="void"!==b[0].name,n="",q="";for(c=0;c<g-2;++c)n+=(0!==c?", ":"")+"arg"+c,q+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+ac(a)+"("+n+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var r=l?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[S,d,e,Nc,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);h&&(q="thisWired"+(0<q.length?", ":"")+q);a+=(m?"var rv = ":"")+"invoker(fn"+(0<q.length?", ":"")+q+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].ec&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",n.push(g+"_dtor"),d.push(b[c].ec));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return Mc(n).apply(null,d)}function Rc(a,b){for(var c=[],d=0;d<a;d++)c.push(B[b+4*d>>2]);return c}var Sc=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Tc(a){4<a&&0===--V[a].Jc&&(V[a]=void 0,Sc.push(a))}
var Cc=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Sc.length?Sc.pop():V.length;V[b]={Jc:1,value:a};return b}};function Ac(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Uc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Aa[c>>2])};case 3:return function(c){return this.fromWireType(Ba[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Vc(a,b,c){switch(b){case 0:return c?function(d){return z[d]}:function(d){return y[d]};case 1:return c?function(d){return ya[d>>1]}:function(d){return za[d>>1]};case 2:return c?function(d){return A[d>>2]}:function(d){return B[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Wc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function Xc(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&za[c];)++c;c<<=1;if(32<c-a&&Wc)return Wc.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ya[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Yc(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ya[b>>1]=a.charCodeAt(e),b+=2;ya[b>>1]=0;return b-d}function Zc(a){return 2*a.length}
function $c(a,b){for(var c=0,d="";!(c>=b/4);){var e=A[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function ad(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}A[b>>2]=g;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d}
function bd(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function cd(a){var b=wa(a)+1,c=dd(b);c&&va(a,z,c,b);return c}
function ed(a,b,c){function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?m[1]:"GMT"}var e=(new Date).getFullYear(),g=new Date(e,0,1),h=new Date(e,6,1);e=g.getTimezoneOffset();var l=h.getTimezoneOffset();A[a>>2]=60*Math.max(e,l);A[b>>2]=Number(e!=l);a=d(g);b=d(h);a=cd(a);b=cd(b);l<e?(B[c>>2]=a,B[c+4>>2]=b):(B[c>>2]=b,B[c+4>>2]=a)}function fd(a,b,c){fd.gd||(fd.gd=!0,ed(a,b,c))}function gd(a){a instanceof oa||"unwind"==a||ea(1,a)}function hd(a){if(!sa)try{a()}catch(b){gd(b)}}var jd;
jd=ia?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var kd={};function ld(){if(!md){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in kd)void 0===kd[b]?delete a[b]:a[b]=kd[b];var c=[];for(b in a)c.push(b+"="+a[b]);md=c}return md}var md;
function nd(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);sa=!0}ea(a,new oa(a))}
function od(a,b,c,d){for(var e=0,g=0;g<c;g++){var h=B[b>>2],l=B[b+4>>2];b+=8;var m=a;var n=h,q=l,r=d,v=z;if(0>q||0>r)throw new J(28);if(null===m.fd)throw new J(8);if(1===(m.flags&2097155))throw new J(8);if(16384===(m.node.mode&61440))throw new J(31);if(!m.Rb.read)throw new J(28);h="undefined"!=typeof r;if(!h)r=m.position;else if(!m.seekable)throw new J(70);n=m.Rb.read(m,v,n,q,r);h||(m.position+=n);m=n;if(0>m)return-1;e+=m;if(m<l)break}return e}
function pd(a){return 0===a%4&&(0!==a%100||0===a%400)}var qd=[31,29,31,30,31,30,31,31,30,31,30,31],rd=[31,28,31,30,31,30,31,31,30,31,30,31];
function sd(a,b,c,d){function e(k,u,D){for(k="number"==typeof k?k.toString():k||"";k.length<u;)k=D[0]+k;return k}function g(k,u){return e(k,u,"0")}function h(k,u){function D(K){return 0>K?-1:0<K?1:0}var G;0===(G=D(k.getFullYear()-u.getFullYear()))&&0===(G=D(k.getMonth()-u.getMonth()))&&(G=D(k.getDate()-u.getDate()));return G}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var u=k.lc;for(k=new Date((new Date(k.mc+1900,0,1)).getTime());0<u;){var D=k.getMonth(),G=(pd(k.getFullYear())?qd:rd)[D];if(u>G-k.getDate())u-=G-k.getDate()+1,k.setDate(1),11>D?k.setMonth(D+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+u);break}}D=new Date(k.getFullYear()+1,0,4);u=l(new Date(k.getFullYear(),
0,4));D=l(D);return 0>=h(u,k)?0>=h(D,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=A[d+40>>2];d={zd:A[d>>2],yd:A[d+4>>2],Cc:A[d+8>>2],Mc:A[d+12>>2],Dc:A[d+16>>2],mc:A[d+20>>2],dc:A[d+24>>2],lc:A[d+28>>2],Fd:A[d+32>>2],xd:A[d+36>>2],Ad:n?x(n):""};c=x(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");n={"%a":function(k){return r[k.dc].substring(0,3)},"%A":function(k){return r[k.dc]},"%b":function(k){return v[k.Dc].substring(0,3)},"%B":function(k){return v[k.Dc]},
"%C":function(k){return g((k.mc+1900)/100|0,2)},"%d":function(k){return g(k.Mc,2)},"%e":function(k){return e(k.Mc,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return g(k.Cc,2)},"%I":function(k){k=k.Cc;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){for(var u=0,D=0;D<=k.Dc-1;u+=(pd(k.mc+1900)?qd:rd)[D++]);return g(k.Mc+u,3)},"%m":function(k){return g(k.Dc+1,2)},"%M":function(k){return g(k.yd,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=
k.Cc&&12>k.Cc?"AM":"PM"},"%S":function(k){return g(k.zd,2)},"%t":function(){return"\t"},"%u":function(k){return k.dc||7},"%U":function(k){return g(Math.floor((k.lc+7-k.dc)/7),2)},"%V":function(k){var u=Math.floor((k.lc+7-(k.dc+6)%7)/7);2>=(k.dc+371-k.lc-2)%7&&u++;if(u)53==u&&(D=(k.dc+371-k.lc)%7,4==D||3==D&&pd(k.mc)||(u=1));else{u=52;var D=(k.dc+7-k.lc-1)%7;(4==D||5==D&&pd(k.mc%400-1))&&u++}return g(u,2)},"%w":function(k){return k.dc},"%W":function(k){return g(Math.floor((k.lc+7-(k.dc+6)%7)/7),2)},
"%y":function(k){return(k.mc+1900).toString().substring(2)},"%Y":function(k){return k.mc+1900},"%z":function(k){k=k.xd;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Ad},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));c=c.replace(/\0\0/g,"%");q=bb(c,!1);if(q.length>b)return 0;z.set(q,a);return q.length-1}
function td(a,b,c,d){var e={string:n=>{var q=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;q=ud(r);va(n,y,q,r)}return q},array:n=>{var q=ud(n.length);z.set(n,q);return q}};a=f["_"+a];var g=[],h=0;if(d)for(var l=0;l<d.length;l++){var m=e[c[l]];m?(0===h&&(h=W()),g[l]=m(d[l])):g[l]=d[l]}c=a.apply(null,g);return c=function(n){0!==h&&X(h);return"string"===b?x(n):"boolean"===b?!!n:n}(c)}
function xb(a,b,c,d){a||(a=this);this.parent=a;this.fc=a.fc;this.qc=null;this.id=qb++;this.name=b;this.mode=c;this.Qb={};this.Rb={};this.rdev=d}Object.defineProperties(xb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Ob();M=Array(4096);Fb(L,"/");O("/tmp",16895,0);O("/home",16895,0);O("/home/web_user",16895,0);
(()=>{O("/dev",16895,0);eb(259,{read:()=>0,write:(b,c,d,e)=>e});Gb("/dev/null",259);db(1280,gb);db(1536,hb);Gb("/dev/tty",1280);Gb("/dev/tty1",1536);var a=$a();Sb("random",a);Sb("urandom",a);O("/dev/shm",16895,0);O("/dev/shm/tmp",16895,0)})();
(()=>{O("/proc",16895,0);var a=O("/proc/self",16895,0);O("/proc/self/fd",16895,0);Fb({fc:()=>{var b=jb(a,"fd",16895,73);b.Qb={lookup:(c,d)=>{var e=pb[+d];if(!e)throw new J(8);c={parent:null,fc:{Uc:"fake"},Qb:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var vd=Array(256),wd=0;256>wd;++wd)vd[wd]=String.fromCharCode(wd);Xb=vd;dc=f.BindingError=cc("BindingError");ec=f.InternalError=cc("InternalError");
uc.prototype.isAliasOf=function(a){if(!(this instanceof uc&&a instanceof uc))return!1;var b=this.Ob.Wb.Tb,c=this.Ob.Pb,d=a.Ob.Wb.Tb;for(a=a.Ob.Pb;b.$b;)c=b.vc(c),b=b.$b;for(;d.$b;)a=d.vc(a),d=d.$b;return b===d&&c===a};
uc.prototype.clone=function(){this.Ob.Pb||hc(this);if(this.Ob.uc)return this.Ob.count.value+=1,this;var a=tc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Ob;a=a(c.call(b,d,{Ob:{value:{count:e.count,oc:e.oc,uc:e.uc,Pb:e.Pb,Wb:e.Wb,Yb:e.Yb,Zb:e.Zb}}}));a.Ob.count.value+=1;a.Ob.oc=!1;return a};uc.prototype["delete"]=function(){this.Ob.Pb||hc(this);this.Ob.oc&&!this.Ob.uc&&S("Object already scheduled for deletion");jc(this);kc(this.Ob);this.Ob.uc||(this.Ob.Yb=void 0,this.Ob.Pb=void 0)};
uc.prototype.isDeleted=function(){return!this.Ob.Pb};uc.prototype.deleteLater=function(){this.Ob.Pb||hc(this);this.Ob.oc&&!this.Ob.uc&&S("Object already scheduled for deletion");nc.push(this);1===nc.length&&pc&&pc(oc);this.Ob.oc=!0;return this};f.getInheritedInstanceCount=function(){return Object.keys(qc).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in qc)qc.hasOwnProperty(b)&&a.push(qc[b]);return a};f.flushPendingDeletes=oc;f.setDelayFunction=function(a){pc=a;nc.length&&pc&&pc(oc)};
U.prototype.ld=function(a){this.Vc&&(a=this.Vc(a));return a};U.prototype.Pc=function(a){this.kc&&this.kc(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=Ec;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.yc?sc(this.Tb.pc,{Wb:this.pd,Pb:c,Zb:this,Yb:a}):sc(this.Tb.pc,{Wb:this,Pb:a})}var c=this.ld(a);if(!c)return this.Pc(a),null;var d=rc(this.Tb,c);if(void 0!==d){if(0===d.Ob.count.value)return d.Ob.Pb=c,d.Ob.Yb=a,d.clone();d=d.clone();this.Pc(a);return d}d=this.Tb.kd(c);d=mc[d];if(!d)return b.call(this);d=this.xc?d.hd:d.pointerType;var e=lc(c,this.Tb,d.Tb);return null===e?b.call(this):this.yc?sc(d.Tb.pc,{Wb:d,Pb:e,Zb:this,Yb:a}):sc(d.Tb.pc,
{Wb:d,Pb:e})};Ic=f.UnboundTypeError=cc("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};
var de={fa:function(a,b){H(a)(b)},s:function(a){return dd(a+24)+24},u:function(a){a=new Ta(a);a.Yc()||(a.Kc(!0),Ra--);a.Lc(!1);Qa.push(a);a.Wc();return a.Zc()},z:function(){Y(0);var a=Qa.pop();if(a.td()&&!a.Tc()){var b=a.md();b&&H(b)(a.tc);Va(a.tc)}Sa=0},a:function(){var a=Sa;if(!a)return Z(0),0;var b=new Ta(a);b.Ec(a);var c=b.hc();if(!c)return Z(0),a;for(var d=0;d<arguments.length;d++){var e=arguments[d];if(0===e||e===c)break;if(xd(e,c,b.Pb+16))return Z(e),a}Z(c);return a},j:function(){var a=Sa;
if(!a)return Z(0),0;var b=new Ta(a);b.Ec(a);var c=b.hc();if(!c)return Z(0),a;for(var d=0;d<arguments.length;d++){var e=arguments[d];if(0===e||e===c)break;if(xd(e,c,b.Pb+16))return Z(e),a}Z(c);return a},y:Va,T:function(){var a=Qa.pop();a||w("no exception to throw");var b=a.tc;a.Tc()||(Qa.push(a),a.Lc(!0),a.Kc(!1),Ra++);Sa=b;throw b;},r:function(a,b,c){(new Ta(a)).$c(b,c);Sa=a;Ra++;throw a;},ca:function(){return Ra},e:function(a){Sa||(Sa=a);throw a;},ua:function(a,b,c){try{b=x(b);b=Tb(a,b);if(c&-8)return-28;
var d=N(b,{wc:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&wb(d,a)?-2:0}catch(e){if("undefined"==typeof P||!(e instanceof J))throw e;return-e.Vb}},oa:function(a,b){try{var c=Q(a);return Ub(Jb,c.path,b)}catch(d){if("undefined"==typeof P||!(d instanceof J))throw d;return-d.Vb}},ka:function(a,b){try{if(0===b)return-28;var c=wa("/")+1;if(b<c)return-68;va("/",y,a,b);return c}catch(d){if("undefined"==typeof P||!(d instanceof J))throw d;return-d.Vb}},la:function(a,b){try{return a=
x(a),Ub(Kb,a,b)}catch(c){if("undefined"==typeof P||!(c instanceof J))throw c;return-c.Vb}},ma:function(a,b,c,d){try{b=x(b);var e=d&256;b=Tb(a,b,d&4096);return Ub(e?Kb:Jb,b,c)}catch(g){if("undefined"==typeof P||!(g instanceof J))throw g;return-g.Vb}},ga:function(a,b,c,d){Vb=d;try{b=x(b);b=Tb(a,b);if(d){Vb+=4;var e=A[Vb-4>>2]}else e=0;return Mb(b,c,e).fd}catch(g){if("undefined"==typeof P||!(g instanceof J))throw g;return-g.Vb}},ea:function(a){try{return a=x(a),Ib(a),0}catch(b){if("undefined"==typeof P||
!(b instanceof J))throw b;return-b.Vb}},na:function(a,b){try{return a=x(a),Ub(Jb,a,b)}catch(c){if("undefined"==typeof P||!(c instanceof J))throw c;return-c.Vb}},L:function(a,b,c){try{b=x(b);b=Tb(a,b);if(0===c){a=b;var d=N(a,{parent:!0}).node;if(!d)throw new J(44);var e=Za(a),g=lb(d,e),h=Bb(d,e,!1);if(h)throw new J(h);if(!d.Qb.unlink)throw new J(63);if(g.qc)throw new J(10);d.Qb.unlink(d,e);vb(g)}else 512===c?Ib(b):w("Invalid flags passed to unlinkat");return 0}catch(l){if("undefined"==typeof P||!(l instanceof
J))throw l;return-l.Vb}},$:function(){},ya:function(a,b,c,d,e){var g=Wb(c);b=R(b);T(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=z;else if(2===c)l=ya;else if(4===c)l=A;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>g])},ec:null})},V:function(a,b,c,d,e,g,h,l,m,n,q,r,v){q=R(q);g=Hc(e,g);l&&(l=Hc(h,l));n&&(n=Hc(m,n));v=Hc(r,v);var k=ac(q);wc(k,function(){Lc("Cannot construct "+
q+" due to unbound types",[d])});gc([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var D=u.Tb;var G=D.pc}else G=uc.prototype;u=bc(k,function(){if(Object.getPrototypeOf(this)!==K)throw new dc("Use 'new' to construct "+q);if(void 0===na.ic)throw new dc(q+" has no accessible constructor");var Oc=na.ic[arguments.length];if(void 0===Oc)throw new dc("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(na.ic).toString()+") parameters instead!");return Oc.apply(this,
arguments)});var K=Object.create(G,{constructor:{value:u}});u.prototype=K;var na=new xc(q,u,K,v,D,g,l,n);D=new U(q,na,!0,!1);G=new U(q+"*",na,!1,!1);var Pc=new U(q+" const*",na,!1,!0);mc[a]={pointerType:G,hd:Pc};Fc(k,u);return[D,G,Pc]})},Ja:function(a,b,c,d,e,g,h){var l=Rc(c,d);b=R(b);g=Hc(e,g);gc([],[a],function(m){function n(){Lc("Cannot call "+q+" due to unbound types",l)}m=m[0];var q=m.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var r=m.Tb.constructor;void 0===r[b]?(n.nc=c-1,r[b]=
n):(vc(r,b,q),r[b].Xb[c-1]=n);gc([],l,function(v){v=[v[0],null].concat(v.slice(1));v=Qc(q,v,null,g,h);void 0===r[b].Xb?(v.nc=c-1,r[b]=v):r[b].Xb[c-1]=v;return[]});return[]})},U:function(a,b,c,d,e,g){0<b||w();var h=Rc(b,c);e=Hc(d,e);gc([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.Tb.ic&&(l.Tb.ic=[]);if(void 0!==l.Tb.ic[b-1])throw new dc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
l.Tb.ic[b-1]=()=>{Lc("Cannot construct "+l.name+" due to unbound types",h)};gc([],h,function(n){n.splice(1,0,null);l.Tb.ic[b-1]=Qc(m,n,null,e,g);return[]});return[]})},t:function(a,b,c,d,e,g,h,l){var m=Rc(c,d);b=R(b);g=Hc(e,g);gc([],[a],function(n){function q(){Lc("Cannot call "+r+" due to unbound types",m)}n=n[0];var r=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&n.Tb.qd.push(b);var v=n.Tb.pc,k=v[b];void 0===k||void 0===k.Xb&&k.className!==n.name&&k.nc===c-2?(q.nc=c-2,q.className=
n.name,v[b]=q):(vc(v,b,r),v[b].Xb[c-2]=q);gc([],m,function(u){u=Qc(r,u,n,g,h);void 0===v[b].Xb?(u.nc=c-2,v[b]=u):v[b].Xb[c-2]=u;return[]});return[]})},xa:function(a,b){b=R(b);T(a,{name:b,fromWireType:function(c){c||S("Cannot use deleted val. handle = "+c);var d=V[c].value;Tc(c);return d},toWireType:function(c,d){return Cc(d)},argPackAdvance:8,readValueFromPointer:Ec,ec:null})},Q:function(a,b,c){c=Wb(c);b=R(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,
readValueFromPointer:Uc(b,c),ec:null})},x:function(a,b,c,d,e){b=R(b);-1===e&&(e=4294967295);e=Wb(c);var g=l=>l;if(0===d){var h=32-8*c;g=l=>l<<h>>>h}c=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};T(a,{name:b,fromWireType:g,toWireType:c,argPackAdvance:8,readValueFromPointer:Vc(b,e,0!==d),ec:null})},q:function(a,b,c){function d(g){g>>=2;var h=B;return new e(xa,h[g+1],h[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];
c=R(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{nd:!0})},P:function(a,b){b=R(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=B[d>>2],g=d+4;if(c)for(var h=g,l=0;l<=e;++l){var m=g+l;if(l==e||0==y[m]){h=x(h,m-h);if(void 0===n)var n=h;else n+=String.fromCharCode(0),n+=h;h=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(y[g+l]);n=n.join("")}I(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"==
typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||S("Cannot pass non-string to std::string");var h=c&&g?wa(e):e.length;var l=dd(4+h+1),m=l+4;B[l>>2]=h;if(c&&g)va(e,y,m,h+1);else if(g)for(g=0;g<h;++g){var n=e.charCodeAt(g);255<n&&(I(m),S("String has UTF-16 code units that do not fit in 8 bits"));y[m+g]=n}else for(g=0;g<h;++g)y[m+g]=e[g];null!==d&&d.push(I,l);return l},argPackAdvance:8,readValueFromPointer:Ec,ec:function(d){I(d)}})},I:function(a,b,c){c=R(c);
if(2===b){var d=Xc;var e=Yc;var g=Zc;var h=()=>za;var l=1}else 4===b&&(d=$c,e=ad,g=bd,h=()=>B,l=2);T(a,{name:c,fromWireType:function(m){for(var n=B[m>>2],q=h(),r,v=m+4,k=0;k<=n;++k){var u=m+4+k*b;if(k==n||0==q[u>>l])v=d(v,u-v),void 0===r?r=v:(r+=String.fromCharCode(0),r+=v),v=u+b}I(m);return r},toWireType:function(m,n){"string"!=typeof n&&S("Cannot pass non-string to C++ string type "+c);var q=g(n),r=dd(4+q+b);B[r>>2]=q>>l;e(n,r+4,q+b);null!==m&&m.push(I,r);return r},argPackAdvance:8,readValueFromPointer:Ec,
ec:function(m){I(m)}})},za:function(a,b){b=R(b);T(a,{Dd:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},qa:function(){return!0},Ga:Tc,Ha:function(a){4<a&&(V[a].Jc+=1)},Ia:function(a,b){var c=Zb[a];void 0===c&&S("_emval_take_value has unknown type "+Jc(a));a=c;a=a.readValueFromPointer(b);return Cc(a)},ra:function(a,b){a=new Date(1E3*(B[a>>2]+4294967296*A[a+4>>2]));A[b>>2]=a.getSeconds();A[b+4>>2]=a.getMinutes();A[b+8>>2]=a.getHours();A[b+12>>2]=a.getDate();A[b+16>>2]=
a.getMonth();A[b+20>>2]=a.getFullYear()-1900;A[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);A[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;A[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();A[b+32>>2]=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0},ha:function(a,b,c,d,e,g,h){try{var l=Q(d);if(0!==(b&2)&&0===(c&2)&&2!==(l.flags&2097155))throw new J(2);if(1===(l.flags&2097155))throw new J(2);if(!l.Rb.Ac)throw new J(43);var m=
l.Rb.Ac(l,a,e,b,c);var n=m.Pb;A[g>>2]=m.dd;B[h>>2]=n;return 0}catch(q){if("undefined"==typeof P||!(q instanceof J))throw q;return-q.Vb}},ia:function(a,b,c,d,e,g){try{var h=Q(e);if(c&2){if(32768!==(h.node.mode&61440))throw new J(43);if(!(d&2)){var l=y.slice(a,a+b);h.Rb.Bc&&h.Rb.Bc(h,l,g,b,d)}}}catch(m){if("undefined"==typeof P||!(m instanceof J))throw m;return-m.Vb}},sa:fd,b:function(){w("")},R:function(a){setTimeout(function(){hd(function(){yd(14)})},1E3*a)},N:function(){return Date.now()},pa:jd,
ta:function(a,b,c){y.copyWithin(a,b,b+c)},da:function(){w("OOM")},va:function(a,b){var c=0;ld().forEach(function(d,e){var g=b+c;e=B[a+4*e>>2]=g;for(g=0;g<d.length;++g)z[e++>>0]=d.charCodeAt(g);z[e>>0]=0;c+=d.length+1});return 0},wa:function(a,b){var c=ld();B[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});B[b>>2]=d;return 0},S:nd,O:function(a){try{var b=Q(a);if(null===b.fd)throw new J(8);b.Fc&&(b.Fc=null);try{b.Rb.close&&b.Rb.close(b)}catch(c){throw c;}finally{pb[b.fd]=null}b.fd=null;
return 0}catch(c){if("undefined"==typeof P||!(c instanceof J))throw c;return c.Vb}},ja:function(a,b){try{var c=Q(a);z[b>>0]=c.tty?2:16384===(c.mode&61440)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){if("undefined"==typeof P||!(d instanceof J))throw d;return d.Vb}},Z:function(a,b,c,d,e,g){try{d=e+2097152>>>0<4194305-!!d?(d>>>0)+4294967296*e:NaN;if(isNaN(d))return 61;var h=Q(a),l=od(h,b,c,d);B[g>>2]=l;return 0}catch(m){if("undefined"==typeof P||!(m instanceof J))throw m;return m.Vb}},M:function(a,
b,c,d){try{var e=Q(a),g=od(e,b,c);B[d>>2]=g;return 0}catch(h){if("undefined"==typeof P||!(h instanceof J))throw h;return h.Vb}},_:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var g=Q(a);Nb(g,b,d);F=[g.position>>>0,(E=g.position,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];A[e>>2]=F[0];A[e+4>>2]=F[1];g.Fc&&0===b&&0===d&&(g.Fc=null);return 0}catch(h){if("undefined"==typeof P||
!(h instanceof J))throw h;return h.Vb}},H:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var g=b=0;g<c;g++){var h=B[a>>2],l=B[a+4>>2];a+=8;var m=e,n=h,q=l,r=void 0,v=z;if(0>q||0>r)throw new J(28);if(null===m.fd)throw new J(8);if(0===(m.flags&2097155))throw new J(8);if(16384===(m.node.mode&61440))throw new J(31);if(!m.Rb.write)throw new J(28);m.seekable&&m.flags&1024&&Nb(m,0,2);var k="undefined"!=typeof r;if(!k)r=m.position;else if(!m.seekable)throw new J(70);var u=m.Rb.write(m,v,n,q,r,void 0);k||(m.position+=
u);var D=u;if(0>D){var G=-1;break a}b+=D}G=b}B[d>>2]=G;return 0}catch(K){if("undefined"==typeof P||!(K instanceof J))throw K;return K.Vb}},Da:zd,F:Ad,Fa:Bd,G:Cd,p:Dd,d:Ed,Ca:Fd,Ea:Gd,c:Hd,h:Id,g:Jd,m:Kd,n:Ld,B:Md,E:Nd,D:Od,J:Pd,aa:Qd,Y:Rd,X:Sd,W:Td,l:Ud,k:Vd,f:Wd,i:Xd,w:Yd,K:Zd,o:$d,v:ae,A:be,C:ce,Ba:sd,ba:function(a,b,c,d){return sd(a,b,c,d)},Aa:function(){t("missing function: wait4");w(-1)}};
(function(){function a(e){f.asm=e.exports;ra=f.asm.Ka;xa=e=ra.buffer;f.HEAP8=z=new Int8Array(e);f.HEAP16=ya=new Int16Array(e);f.HEAP32=A=new Int32Array(e);f.HEAPU8=y=new Uint8Array(e);f.HEAPU16=za=new Uint16Array(e);f.HEAPU32=B=new Uint32Array(e);f.HEAPF32=Aa=new Float32Array(e);f.HEAPF64=Ba=new Float64Array(e);Ca=f.asm.Oa;Ea.unshift(f.asm.La);Ia--;f.monitorRunDependencies&&f.monitorRunDependencies(Ia);0==Ia&&(null!==Ja&&(clearInterval(Ja),Ja=null),Ka&&(e=Ka,Ka=null,e()))}function b(e){a(e.instance)}
function c(e){return Oa().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){t("failed to asynchronously prepare wasm: "+g);w(g)})}var d={a:de};Ia++;f.monitorRunDependencies&&f.monitorRunDependencies(Ia);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){t("Module.instantiateWasm callback failed with error: "+e),ba(e)}(function(){return qa||"function"!=typeof WebAssembly.instantiateStreaming||La()||C.startsWith("file://")||ia||"function"!=
typeof fetch?c(b):fetch(C,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){t("wasm streaming compile failed: "+g);t("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.La).apply(null,arguments)};var I=f._free=function(){return(I=f._free=f.asm.Ma).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Na).apply(null,arguments)};
var dd=f._malloc=function(){return(dd=f._malloc=f.asm.Pa).apply(null,arguments)},Z=f.setTempRet0=function(){return(Z=f.setTempRet0=f.asm.Qa).apply(null,arguments)},yd=f._raise=function(){return(yd=f._raise=f.asm.Ra).apply(null,arguments)},Kc=f.___getTypeName=function(){return(Kc=f.___getTypeName=f.asm.Sa).apply(null,arguments)};f.__embind_initialize_bindings=function(){return(f.__embind_initialize_bindings=f.asm.Ta).apply(null,arguments)};
var mb=f._emscripten_builtin_memalign=function(){return(mb=f._emscripten_builtin_memalign=f.asm.Ua).apply(null,arguments)},Y=f._setThrew=function(){return(Y=f._setThrew=f.asm.Va).apply(null,arguments)},W=f.stackSave=function(){return(W=f.stackSave=f.asm.Wa).apply(null,arguments)},X=f.stackRestore=function(){return(X=f.stackRestore=f.asm.Xa).apply(null,arguments)},ud=f.stackAlloc=function(){return(ud=f.stackAlloc=f.asm.Ya).apply(null,arguments)},xd=f.___cxa_can_catch=function(){return(xd=f.___cxa_can_catch=
f.asm.Za).apply(null,arguments)},Ua=f.___cxa_is_pointer_type=function(){return(Ua=f.___cxa_is_pointer_type=f.asm._a).apply(null,arguments)},ee=f.dynCall_iij=function(){return(ee=f.dynCall_iij=f.asm.$a).apply(null,arguments)};f.dynCall_iiij=function(){return(f.dynCall_iiij=f.asm.ab).apply(null,arguments)};f.dynCall_viiiiiji=function(){return(f.dynCall_viiiiiji=f.asm.bb).apply(null,arguments)};f.dynCall_iiiijji=function(){return(f.dynCall_iiiijji=f.asm.cb).apply(null,arguments)};
f.dynCall_iiiiijji=function(){return(f.dynCall_iiiiijji=f.asm.db).apply(null,arguments)};f.dynCall_viiiij=function(){return(f.dynCall_viiiij=f.asm.eb).apply(null,arguments)};f.dynCall_jiij=function(){return(f.dynCall_jiij=f.asm.fb).apply(null,arguments)};f.dynCall_jiii=function(){return(f.dynCall_jiii=f.asm.gb).apply(null,arguments)};f.dynCall_iiiij=function(){return(f.dynCall_iiiij=f.asm.hb).apply(null,arguments)};f.dynCall_viiij=function(){return(f.dynCall_viiij=f.asm.ib).apply(null,arguments)};
f.dynCall_iiiiiij=function(){return(f.dynCall_iiiiiij=f.asm.jb).apply(null,arguments)};f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.kb).apply(null,arguments)};f.dynCall_iiijjii=function(){return(f.dynCall_iiijjii=f.asm.lb).apply(null,arguments)};f.dynCall_iiiijijii=function(){return(f.dynCall_iiiijijii=f.asm.mb).apply(null,arguments)};f.dynCall_viiiijiji=function(){return(f.dynCall_viiiijiji=f.asm.nb).apply(null,arguments)};
f.dynCall_iiiiijii=function(){return(f.dynCall_iiiiijii=f.asm.ob).apply(null,arguments)};f.dynCall_viijiii=function(){return(f.dynCall_viijiii=f.asm.pb).apply(null,arguments)};f.dynCall_viiiiijii=function(){return(f.dynCall_viiiiijii=f.asm.qb).apply(null,arguments)};f.dynCall_iiiijiii=function(){return(f.dynCall_iiiijiii=f.asm.rb).apply(null,arguments)};f.dynCall_iiijii=function(){return(f.dynCall_iiijii=f.asm.sb).apply(null,arguments)};
f.dynCall_iiiji=function(){return(f.dynCall_iiiji=f.asm.tb).apply(null,arguments)};f.dynCall_viij=function(){return(f.dynCall_viij=f.asm.ub).apply(null,arguments)};f.dynCall_viji=function(){return(f.dynCall_viji=f.asm.vb).apply(null,arguments)};f.dynCall_vijii=function(){return(f.dynCall_vijii=f.asm.wb).apply(null,arguments)};var fe=f.dynCall_ji=function(){return(fe=f.dynCall_ji=f.asm.xb).apply(null,arguments)};f.dynCall_vij=function(){return(f.dynCall_vij=f.asm.yb).apply(null,arguments)};
f.dynCall_viiiji=function(){return(f.dynCall_viiiji=f.asm.zb).apply(null,arguments)};f.dynCall_viijji=function(){return(f.dynCall_viijji=f.asm.Ab).apply(null,arguments)};f.dynCall_viiji=function(){return(f.dynCall_viiji=f.asm.Bb).apply(null,arguments)};f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.Cb).apply(null,arguments)};f.dynCall_viiijii=function(){return(f.dynCall_viiijii=f.asm.Db).apply(null,arguments)};f.dynCall_vijjii=function(){return(f.dynCall_vijjii=f.asm.Eb).apply(null,arguments)};
f.dynCall_vijj=function(){return(f.dynCall_vijj=f.asm.Fb).apply(null,arguments)};f.dynCall_vijjj=function(){return(f.dynCall_vijjj=f.asm.Gb).apply(null,arguments)};f.dynCall_vijjjji=function(){return(f.dynCall_vijjjji=f.asm.Hb).apply(null,arguments)};f.dynCall_vijiii=function(){return(f.dynCall_vijiii=f.asm.Ib).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.Jb).apply(null,arguments)};
var ge=f.dynCall_j=function(){return(ge=f.dynCall_j=f.asm.Kb).apply(null,arguments)},he=f.dynCall_jiiii=function(){return(he=f.dynCall_jiiii=f.asm.Lb).apply(null,arguments)};f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.Mb).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.Nb).apply(null,arguments)};function Hd(a,b,c){var d=W();try{return H(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}
function Yd(a,b,c,d,e){var g=W();try{H(a)(b,c,d,e)}catch(h){X(g);if(h!==h+0)throw h;Y(1,0)}}function Ed(a,b){var c=W();try{return H(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Id(a,b,c,d){var e=W();try{return H(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;Y(1,0)}}function Vd(a,b){var c=W();try{H(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Wd(a,b,c){var d=W();try{H(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}
function Ld(a,b,c,d,e,g,h){var l=W();try{return H(a)(b,c,d,e,g,h)}catch(m){X(l);if(m!==m+0)throw m;Y(1,0)}}function Ud(a){var b=W();try{H(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function Xd(a,b,c,d){var e=W();try{H(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;Y(1,0)}}function Kd(a,b,c,d,e,g){var h=W();try{return H(a)(b,c,d,e,g)}catch(l){X(h);if(l!==l+0)throw l;Y(1,0)}}function Jd(a,b,c,d,e){var g=W();try{return H(a)(b,c,d,e)}catch(h){X(g);if(h!==h+0)throw h;Y(1,0)}}
function Bd(a,b,c){var d=W();try{return H(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Gd(a,b,c,d){var e=W();try{return H(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;Y(1,0)}}function zd(a,b,c){var d=W();try{return H(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Fd(a,b,c,d){var e=W();try{return H(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;Y(1,0)}}function $d(a,b,c,d,e,g,h){var l=W();try{H(a)(b,c,d,e,g,h)}catch(m){X(l);if(m!==m+0)throw m;Y(1,0)}}
function Zd(a,b,c,d,e,g){var h=W();try{H(a)(b,c,d,e,g)}catch(l){X(h);if(l!==l+0)throw l;Y(1,0)}}function Nd(a,b,c,d,e,g,h,l,m,n){var q=W();try{return H(a)(b,c,d,e,g,h,l,m,n)}catch(r){X(q);if(r!==r+0)throw r;Y(1,0)}}function Pd(a,b,c,d,e,g,h,l,m,n,q,r,v){var k=W();try{return H(a)(b,c,d,e,g,h,l,m,n,q,r,v)}catch(u){X(k);if(u!==u+0)throw u;Y(1,0)}}function Md(a,b,c,d,e,g,h,l){var m=W();try{return H(a)(b,c,d,e,g,h,l)}catch(n){X(m);if(n!==n+0)throw n;Y(1,0)}}
function Dd(a){var b=W();try{return H(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function Cd(a,b,c,d){var e=W();try{return H(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;Y(1,0)}}function Ad(a,b,c,d){var e=W();try{return H(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;Y(1,0)}}function ae(a,b,c,d,e,g,h,l){var m=W();try{H(a)(b,c,d,e,g,h,l)}catch(n){X(m);if(n!==n+0)throw n;Y(1,0)}}
function Od(a,b,c,d,e,g,h,l,m,n,q,r){var v=W();try{return H(a)(b,c,d,e,g,h,l,m,n,q,r)}catch(k){X(v);if(k!==k+0)throw k;Y(1,0)}}function be(a,b,c,d,e,g,h,l,m,n,q){var r=W();try{H(a)(b,c,d,e,g,h,l,m,n,q)}catch(v){X(r);if(v!==v+0)throw v;Y(1,0)}}function ce(a,b,c,d,e,g,h,l,m,n,q,r,v,k,u,D){var G=W();try{H(a)(b,c,d,e,g,h,l,m,n,q,r,v,k,u,D)}catch(K){X(G);if(K!==K+0)throw K;Y(1,0)}}function Qd(a,b,c,d){var e=W();try{return ee(a,b,c,d)}catch(g){X(e);if(g!==g+0)throw g;Y(1,0)}}
function Rd(a){var b=W();try{return ge(a)}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function Sd(a,b){var c=W();try{return fe(a,b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Td(a,b,c,d,e){var g=W();try{return he(a,b,c,d,e)}catch(h){X(g);if(h!==h+0)throw h;Y(1,0)}}f.ccall=td;f.cwrap=function(a,b,c,d){c=c||[];var e=c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&e&&!d?f["_"+a]:function(){return td(a,b,c,arguments,d)}};var ie;Ka=function je(){ie||ke();ie||(Ka=je)};
function ke(){function a(){if(!ie&&(ie=!0,f.calledRun=!0,!sa)){f.noFSInit||Pb||(Pb=!0,Ob(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Sb("stdin",f.stdin):Hb("/dev/tty","/dev/stdin"),f.stdout?Sb("stdout",null,f.stdout):Hb("/dev/tty","/dev/stdout"),f.stderr?Sb("stderr",null,f.stderr):Hb("/dev/tty1","/dev/stderr"),Mb("/dev/stdin",0),Mb("/dev/stdout",1),Mb("/dev/stderr",1));rb=!1;Pa(Ea);Pa(Fa);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(le){var b=f._main;try{var c=b(0,
0);nd(c,!0)}catch(d){gd(d)}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),Ga.unshift(b);Pa(Ga)}}if(!(0<Ia)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ha();Pa(Da);0<Ia||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();
var le=!0;f.noInitialRun&&(le=!1);ke();


  return createGlobalModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createGlobalModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createGlobalModule; });
else if (typeof exports === 'object')
  exports["createGlobalModule"] = createGlobalModule;
